/* Dashboard */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;

  App.screens.dashboard = {
    title: 'Dashboard',
    actions() { const w = S.settings.widgets; return `<div class="popwrap hide-m"><button type="button" class="btn" data-pop="layout">${I.layout}<span>Layout</span></button><div class="popover" id="pop-layout"><div class="sec">Widgets</div>${Object.entries(S.WIDGETS).map(([k, l]) => `<button type="button" class="item" data-action="widget" data-value="${k}" aria-checked="${w[k] !== false}">${w[k] !== false ? I.check : '<span style="width:15px"></span>'} ${esc(l)}</button>`).join('')}</div></div>`; },
    render(ctx) {
      const list = ctx.inRange, all = ctx.all; const w = S.settings.widgets; const s = C.summary(list); const days = C.dailyAggregation(list); const ds = C.daySummary(days); const account = App.account();
      const parts = [];
      /* Tilt-Warnungen & Hinweise */
      const todayKey = C.dayKey(new Date());
      if (S.settings.tiltWarnings) { const tilt = C.tiltCheck(App.todayTrades(all), { account, dailyLossLimitPct: S.settings.dailyLossLimitPct / 100 }); for (const wn of tilt.warnings) { if (S.data.dismissed[wn.kind] === todayKey) continue; parts.push(U.banner(wn.severity === 'critical' ? 'loss' : 'warn', wn.title, wn.text, { close: 'dismiss-tilt' }).replace('data-action="dismiss-tilt"', `data-action="dismiss" data-key="${wn.kind}"`)); } }
      if (!S.day(todayKey)?.checkIn && !S.activeSession() && new Date().getDay() % 6 !== 0 && S.data.dismissed.checkin !== todayKey) parts.push(U.banner('info', 'Noch kein Check-in heute', 'Schlaf, Stress und Stimmung dauern 20 Sekunden und zeigen dir später, wann du wirklich gut handelst.', { icon: 'sparkle', close: 'x', trailing: `<button type="button" class="btn sm primary" data-action="start-session">${I.play} Session starten</button>` }).replace('data-action="x"', 'data-action="dismiss" data-key="checkin"'));
      if (!all.length) parts.push(U.banner('accent', 'Willkommen', 'Dein Journal ist noch leer. Logge deinen ersten Trade, importiere eine CSV oder lade Beispieldaten, um alle Auswertungen zu sehen.', { icon: 'sparkle', trailing: `<button type="button" class="btn sm" data-action="import">${I.upload} CSV</button><button type="button" class="btn sm primary" data-action="install-sample">Beispieldaten laden</button>` }));
      else if (S.settings.sampleInstalled) parts.push(`<div class="row between small muted" style="padding:0 4px"><span>Beispieldaten sind geladen. Alle Zahlen sind Beispiele.</span><button type="button" class="btn xs ghost" data-action="remove-sample">Beispieldaten entfernen</button></div>`);

      /* Kennzahlen */
      if (w.kpis !== false) {
        const wl = s.avgLoss < 0 ? s.avgWin / -s.avgLoss : null; const maxWL = Math.max(s.avgWin, -s.avgLoss, 1);
        parts.push(`<div class="grid tiles">
          ${U.tile('Netto-P&L', U.pnl(s.total, '', { signed: false }), { n: `${s.n} Trades`, info: 'Summe aller abgeschlossenen Trades im Zeitraum nach Gebühren.', foot: s.n ? `Ø ${fmt.cur(s.expectancy, { signed: true })} pro Trade` : 'Noch keine Trades' })}
          ${U.tile('Profit-Faktor', s.n ? fmt.factor(s.pf) : '—', { info: 'Bruttogewinn geteilt durch Bruttoverlust. Über 1,5 ist gut.', gauge: U.donut([{ v: s.gp, c: 'profit' }, { v: -s.gl, c: 'loss' }], 54, 8), foot: s.n ? `${fmt.cur(s.gp, { compact: true })} zu ${fmt.cur(s.gl, { compact: true })}` : '' })}
          ${U.tile('Trade-Win-Rate', fmt.pct(s.winRate, 1), { info: 'Anteil der Gewinn-Trades. Break-even-Trades zählen nicht als Gewinn.', gauge: U.semiGauge([{ v: s.wins, c: 'profit' }, { v: s.be, c: 'be' }, { v: s.losses, c: 'loss' }], ''), foot: `<span class="pills">${U.pill(s.wins, 'win')}${U.pill(s.be, 'be')}${U.pill(s.losses, 'loss')}</span>` })}
          ${U.tile('Tages-Win-Rate', fmt.pct(ds.dayWinRate, 1), { info: 'Anteil der Handelstage mit positivem Ergebnis.', gauge: U.semiGauge([{ v: ds.winDays, c: 'profit' }, { v: ds.days - ds.winDays - ds.lossDays, c: 'be' }, { v: ds.lossDays, c: 'loss' }], ''), foot: `<span class="pills">${U.pill(ds.winDays, 'win')}${U.pill(ds.days - ds.winDays - ds.lossDays, 'be')}${U.pill(ds.lossDays, 'loss')}</span>` })}
          ${U.tile('Ø Gewinn / Verlust', wl == null ? (s.avgWin > 0 ? '∞' : '—') : fmt.num(wl, 2), { info: 'Durchschnittlicher Gewinn-Trade geteilt durch durchschnittlichen Verlust-Trade.', gauge: `<div class="wl-bars"><div class="track"><i style="width:${s.avgWin / maxWL * 100}%;background:var(--profit)"></i></div><div class="track"><i style="width:${-s.avgLoss / maxWL * 100}%;background:var(--loss)"></i></div></div>`, foot: `<span class="pos">${fmt.cur(s.avgWin)}</span> · <span class="neg">${fmt.cur(s.avgLoss)}</span>` })}
        </div>`);
      }
      /* Score + P&L */
      const row2 = [];
      if (w.pnl !== false) { const id = 'dash-pnl'; U.chartData[id] = { days }; row2.push(U.card('Täglicher & kumulierter P&L', `<div class="chart h280" data-chart="pnl" data-id="${id}"></div><div class="legend"><span><i style="background:var(--profit);opacity:.6"></i>Tages-P&L</span><span><i style="background:var(--profit)"></i>Kumuliert</span></div>`, { info: 'Balken zeigen das Tagesergebnis, die Linie den kumulierten Verlauf.' })); }
      if (w.score !== false) { const sc = C.traderScore(list, account); row2.push(U.card('Journal-Score', `<div class="score-wrap">${U.radar(sc.axes, 250)}<div class="score-scale"><div class="track"></div><div class="knob" style="left:${sc.overall}%"></div><div class="lbls"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div></div><div class="row between" style="margin-top:14px"><span class="muted small">Dein Score</span><span class="score-big" style="color:${U.scoreColor(sc.overall)}">${sc.overall}</span></div></div>`, { info: 'Sechs Achsen von 0 bis 100: Win-Rate, Profit-Faktor, Gewinn/Verlust-Verhältnis, Konsistenz, Regeltreue und Drawdown.' })); }
      if (row2.length) parts.push(`<div class="grid main-side">${row2.join('')}</div>`);
      /* Reihe 3 */
      const row3 = [];
      if (w.winloss !== false) row3.push(U.card('Ø Gewinn / Verlust pro Trade', `<div class="row between" style="align-items:flex-start"><div><div class="score-big">${U.pnl(s.expectancy)}</div><div class="muted small">Erwartungswert pro Trade</div></div><div class="row" style="gap:16px">${U.donut([{ v: s.wins, c: 'profit' }, { v: s.losses + s.be, c: 'surface-3' }], 64, 8, `<span class="pos">${fmt.pct(s.winRate)}</span>`)}${U.donut([{ v: s.avgWin, c: 'profit' }, { v: -s.avgLoss, c: 'loss' }], 64, 8, `<span class="small">${s.payoff == null ? '∞' : fmt.num(s.payoff, 1)}</span>`)}</div></div><div class="divider"></div>${U.kv('Ø Gewinn-Trade', `<span class="pos">${fmt.cur(s.avgWin)}</span>`)}${U.kv('Ø Verlust-Trade', `<span class="neg">${fmt.cur(s.avgLoss)}</span>`)}${U.kv('Größter Gewinn', `<span class="pos">${fmt.cur(s.largestWin)}</span>`)}${U.kv('Größter Verlust', `<span class="neg">${fmt.cur(s.largestLoss)}</span>`)}${U.kv('Max. Drawdown', `<span class="neg">${fmt.cur(-s.maxDD)}</span>`)}`, { info: 'Wie stehen deine Gewinner zu deinen Verlierern?' }));
      if (w.discipline !== false) { const disc = C.avgDiscipline(list); const mr = C.mistakeReport(list); row3.push(U.card('Disziplin & Fehlerkosten', `<div class="row" style="gap:18px;align-items:center">${U.ring(disc, 96, 9, 'Score')}<div class="grow"><div class="kv"><span>Trades ohne Fehler</span><b>${mr.n ? `${mr.compliantN} von ${mr.n}` : '—'}</b></div><div class="kv"><span>Fehler haben gekostet</span><b class="${mr.cost < -C.EPS ? 'neg' : 'neu'}">${mr.n ? fmt.cur(mr.cost, { signed: true }) : '—'}</b></div><div class="kv"><span>Ergebnis ohne Fehler</span><b class="${U.cls(mr.compliant)}">${mr.n ? fmt.cur(mr.compliant, { signed: true }) : '—'}</b></div></div></div>${mr.items.length ? `<div class="divider"></div>${mr.items.slice(0, 3).map(it => U.barRow(it.name, it.total, Math.max(...mr.items.map(x => Math.abs(x.total)), 1), `${fmt.cur(it.total, { signed: true })} · ${it.n}×`, it.total < 0 ? 'var(--loss)' : 'var(--profit)')).join('')}` : ''}`, { info: 'Disziplin-Score aus Plan, Einstieg, Stop, Fehler-Tags und Regeln. Fehlerkosten: Ergebnis mit minus Ergebnis ohne Trades mit Fehler-Tags.' })); }
      if (w.strategy !== false) { const strategies = S.data.strategies; const groups = C.groupBy(list, t => t.strategy || null); const body = strategies.length || groups.length ? (groups.length ? `<div class="stack" style="gap:2px">${groups.map(g => { const max = Math.max(...groups.map(x => Math.abs(x.s.total)), 1); return `<div class="bar-row"><div class="bl"><span>${esc(g.key)} <span class="muted">· ${g.s.n} Trades · WR ${fmt.pct(g.s.winRate)}</span></span><b class="${U.cls(g.s.total)}">${fmt.cur(g.s.total, { signed: true })}</b></div><div class="track"><i style="width:${Math.abs(g.s.total) / max * 100}%;background:var(--${g.s.total >= 0 ? 'profit' : 'loss'})"></i></div></div>`; }).join('')}</div>` : U.empty('strategy', 'Noch keine Trades mit Strategie', 'Weise Trades im Editor einer Strategie zu.')) : U.empty('strategy', 'Keine Strategien vorhanden', 'Lege unter „Strategien“ deine Ansätze an und ordne Trades zu.', `<a class="btn sm" href="#/strategy">${I.plus} Strategie anlegen</a>`); row3.push(U.card('Strategie-Performance', body, { info: 'Netto-P&L je Strategie im Zeitraum.' })); }
      if (row3.length) parts.push(`<div class="grid three">${row3.join('')}</div>`);
      /* Kalender + letzte Trades */
      const row4 = [];
      if (w.calendar !== false) { const m = App.state.calMonth || new Date(new Date().getFullYear(), new Date().getMonth(), 1); const daysAll = C.dailyAggregation(all); row4.push(U.card(fmt.monthYear(m), calendarHTML(daysAll, m.getFullYear(), m.getMonth(), account), { trailing: `<div class="cal-nav"><button type="button" class="btn round accent" data-action="cal-prev" aria-label="Voriger Monat">${I.chevL}</button><button type="button" class="btn round accent" data-action="cal-next" aria-label="Nächster Monat">${I.chevR}</button></div>`, sub: monthSub(daysAll, m) })); }
      if (w.recent !== false) { const recent = all.slice().sort((a, b) => b.sortTime - a.sortTime).slice(0, 8); const open = all.filter(t => !t.closed); row4.push(U.card('Letzte Trades', recent.length ? `<div class="tbl-wrap inset"><table class="tbl compact" style="min-width:0"><thead><tr><th>Datum</th><th>Symbol</th><th class="r">Netto-P&L</th></tr></thead><tbody>${recent.map(t => `<tr class="link" data-action="trade" data-id="${t.id}"><td>${fmt.dateFull(t.close || t.open)}<div class="sub">${fmt.time(t.close || t.open)}</div></td><td class="sym">${esc(t.symbol)} ${U.badge(t.direction)}</td><td class="r">${t.closed ? U.pnl(t.pnl) : U.pill('offen', 'open')}</td></tr>`).join('')}</tbody></table></div>` : U.empty('tradelog', 'Keine Trades', 'Logge deinen ersten Trade.'), { sub: open.length ? `${open.length} offene Position${open.length > 1 ? 'en' : ''}` : '', trailing: `<a class="btn sm ghost" href="#/trades">Alle ${I.chevR}</a>` })); }
      if (row4.length) parts.push(`<div class="grid main-side">${row4.join('')}</div>`);
      return parts.join('');
    },
  };
  function monthSub(days, m) { const inM = days.filter(d => d.day.getFullYear() === m.getFullYear() && d.day.getMonth() === m.getMonth()); const total = C.sum(inM.map(d => d.pnl)); return inM.length ? `Monat: <b class="${U.cls(total)}">${fmt.cur(total, { signed: true })}</b> · ${inM.length} Handelstage` : 'Keine Trades in diesem Monat'; }
  function calendarHTML(days, year, month, account) {
    const weeks = C.calendarMonth(days, year, month); const today = C.dayKey(new Date()); const sel = App.state.route === 'day' ? App.state.params[0] : null;
    let html = C.WEEKDAYS.map(w => `<div class="wd">${w}</div>`).join('') + '<div class="wd wk"></div>';
    for (const wk of weeks) {
      html += wk.cells.map(c => { if (!c) return '<div class="d pad"></div>'; const e = c.entry; const k = e ? (e.pnl > C.EPS ? 'win' : e.pnl < -C.EPS ? 'loss' : 'be') : ''; return `<div class="d ${k} ${c.key === today ? 'today' : ''} ${c.key === sel ? 'sel' : ''}" data-action="day" data-day="${c.key}" role="button" tabindex="0"><span class="n">${String(c.date.getDate()).padStart(2, '0')}</span>${e ? `<span class="p ${U.cls(e.pnl)}">${fmt.cur(e.pnl, { signed: true, compact: true })}</span><span class="c">${e.n} Trade${e.n === 1 ? '' : 's'}</span>` : ''}</div>`; }).join('');
      html += `<div class="w"><span class="t">Woche ${wk.index}</span><span class="p ${wk.days ? U.cls(wk.pnl) : 'faint'}">${wk.days ? fmt.cur(wk.pnl, { signed: true, compact: true }) : '—'}</span>${wk.days ? `<span class="c">${fmt.pct(wk.winRate)} Tage im Plus</span>` : ''}<span class="days">${wk.days} Tag${wk.days === 1 ? '' : 'e'}</span></div>`;
    }
    return `<div class="cal">${html}</div>`;
  }
  App.calendarHTML = calendarHTML;
  Object.assign(App.actions, {
    widget(el) { const w = Object.assign({}, S.settings.widgets); w[el.dataset.value] = w[el.dataset.value] === false; S.setSetting('widgets', w); App.rerender(); },
    'cal-prev'() { const m = App.state.calMonth || new Date(); App.state.calMonth = new Date(m.getFullYear(), m.getMonth() - 1, 1); App.rerender(); },
    'cal-next'() { const m = App.state.calMonth || new Date(); App.state.calMonth = new Date(m.getFullYear(), m.getMonth() + 1, 1); App.rerender(); },
  });
})(typeof self !== 'undefined' ? self : this);
