/* Tagesansicht */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;
  App.screens.day = {
    title: 'Tagesansicht',
    render(ctx) {
      const key = ctx.params[0] || C.dayKey(new Date()); const date = C.parseDayKey(key); if (isNaN(date)) return U.empty('day', 'Ungültiges Datum', '');
      const all = ctx.all; const trades = all.filter(t => t.dayKey === key).sort((a, b) => a.open - b.open); const closed = trades.filter(t => t.closed); const s = C.summary(closed); const d = S.day(key) || {}; const rules = S.data.rules.filter(r => r.active !== false); const followed = d.rulesFollowed || [];
      const prev = new Date(date); prev.setDate(prev.getDate() - 1); const next = new Date(date); next.setDate(next.getDate() + 1); const isToday = key === C.dayKey(new Date());
      const nav = `<div class="row between"><div class="row"><a class="btn round" href="#/day/${C.dayKey(prev)}" aria-label="Voriger Tag">${I.chevL}</a><a class="btn round" href="#/day/${C.dayKey(next)}" aria-label="Nächster Tag">${I.chevR}</a><h2 style="font-size:18px;margin-left:6px">${fmt.weekdayLong(date)}</h2>${isToday ? U.pill('Heute', 'win') : ''}</div><div class="row">${!isToday ? `<a class="btn sm ghost" href="#/day/${C.dayKey(new Date())}">Heute</a>` : ''}<button type="button" class="btn sm" data-action="check-in" data-day="${key}">${I.sparkle} ${d.checkIn ? 'Check-in bearbeiten' : 'Check-in'}</button><button type="button" class="btn sm accent" data-action="new-trade-day" data-day="${key}">${I.plus} Trade für diesen Tag</button></div></div>`;
      let c = 0; const id = 'day-spark'; U.chartData[id] = { values: closed.sort((a, b) => a.close - b.close).map(t => (c += t.pnl)) };
      const stats = U.card('', `<div class="row" style="gap:20px;align-items:flex-start"><div><div class="caption">Netto-P&L</div><div class="score-big ${U.cls(s.total)}">${closed.length ? fmt.cur(s.total, { signed: true }) : '—'}</div></div><div class="grow chart h80" data-chart="spark" data-id="${id}" style="min-width:160px"></div></div><div class="day-card"><div class="stats"><div><div class="k">Trades</div><div class="v">${trades.length}${trades.length - closed.length ? ` <span class="muted small">(${trades.length - closed.length} offen)</span>` : ''}</div></div><div><div class="k">Brutto-P&L</div><div class="v ${U.cls(s.gross)}">${fmt.cur(s.gross, { signed: true })}</div></div><div><div class="k">Gewinner / Verlierer</div><div class="v"><span class="pos">${s.wins}</span> / <span class="neg">${s.losses}</span></div></div><div><div class="k">Gebühren</div><div class="v">${fmt.cur(s.fees)}</div></div><div><div class="k">Win-Rate</div><div class="v">${closed.length ? fmt.pct(s.winRate) : '—'}</div></div><div><div class="k">Volumen</div><div class="v">${fmt.num(s.volume, 2)}</div></div><div><div class="k">Profit-Faktor</div><div class="v">${closed.length ? fmt.factor(s.pf) : '—'}</div></div><div><div class="k">Ø R</div><div class="v">${s.avgR != null ? fmt.r(s.avgR) : '—'}</div></div></div></div>`);
      const tradesCard = U.card('Trades des Tages', trades.length ? `<div class="tbl-wrap inset"><table class="tbl compact" style="min-width:560px"><thead><tr><th>Zeit</th><th>Symbol</th><th>Setup</th><th>Status</th><th class="r">Netto-P&L</th><th class="r">R</th><th class="r">Score</th></tr></thead><tbody>${trades.map(t => { const sc = C.discipline(t).score; return `<tr class="link" data-action="trade" data-id="${t.id}"><td>${fmt.time(t.open)}${t.close ? ` – ${fmt.time(t.close)}` : ''}</td><td class="sym">${esc(t.symbol)} ${U.badge(t.direction)}</td><td>${t.setup ? U.chip(t.setup, 'setup') : '—'}${t.mistakes.length ? ' ' + t.mistakes.map(m => U.chip(m, 'mistake')).join(' ') : ''}</td><td>${U.statusPill(t.status)}</td><td class="r">${t.closed ? U.pnl(t.pnl) : '—'}</td><td class="r">${U.rText(t.r)}</td><td class="r"><b style="color:${U.scoreColor(sc)}">${sc}</b></td></tr>`; }).join('')}</tbody></table></div>` : U.empty('tradelog', 'Keine Trades an diesem Tag', isToday ? 'Ein ruhiger Tag ist auch ein guter Tag.' : ''));
      const ci = d.checkIn; const checkCard = U.card('Check-in', ci ? `<div class="grid" style="grid-template-columns:repeat(3,1fr);gap:8px">${[['Schlaf', ci.sleep != null ? fmt.num(ci.sleep, 1) + ' h' : '—'], ['Stress', ci.stress != null ? ci.stress + ' / 5' : '—'], ['Stimmung', ci.mood != null ? ci.mood + ' / 5' : '—']].map(([k, v]) => `<div class="strat-stats" style="margin:0;grid-template-columns:1fr"><div><div class="k">${k}</div><div class="v">${v}</div></div></div>`).join('')}</div>${ci.goal ? `<div class="small" style="margin-top:10px"><span class="muted">Fokus:</span> ${esc(ci.goal)}</div>` : ''}${ci.note ? `<div class="small" style="margin-top:6px"><span class="muted">Notiz:</span> ${esc(ci.note)}</div>` : ''}` : U.empty('sparkle', 'Kein Check-in', 'Schlaf, Stress und Stimmung vor dem Handel festhalten.', `<button type="button" class="btn sm" data-action="check-in" data-day="${key}">Check-in nachtragen</button>`));
      const reg = d.regime || {}; const regimeCard = U.card('Marktphase', `<div class="form-grid"><div class="field"><span class="lbl">Trend</span>${U.seg([['trending', 'Trend'], ['ranging', 'Seitwärts']], reg.trend || '', 'day-regime').replace(/data-action="day-regime"/g, `data-action="day-regime" data-day="${key}" data-kind="trend"`)}</div><div class="field"><span class="lbl">Volatilität</span>${U.seg([['low', 'niedrig'], ['normal', 'normal'], ['high', 'hoch']], reg.vol || '', 'day-regime').replace(/data-action="day-regime"/g, `data-action="day-regime" data-day="${key}" data-kind="vol"`)}</div></div>`, { info: 'Die Marktphase des Tages fließt in die Auswertung „Marktphase“ ein.' });
      const rulesCard = U.card('Regeln des Tages', rules.length ? `<div class="checklist">${rules.map(r => `<div class="it toggle ${followed.includes(r.id) ? 'done' : ''}" data-action="day-rule" data-day="${key}" data-rule="${r.id}"><span class="box">${I.check}</span><span>${esc(r.text)}</span></div>`).join('')}</div><div class="small muted" style="margin-top:8px">${rules.length ? `${followed.filter(f => rules.some(r => r.id === f)).length} von ${rules.length} eingehalten` : ''}</div>` : U.empty('shield', 'Keine Regeln definiert', 'Lege deine Handelsregeln in den Einstellungen an.', `<a class="btn sm" href="#/settings">Regeln anlegen</a>`), { info: 'Abhaken, welche Regeln du heute eingehalten hast. Die Quote erscheint im Fortschritt.' });
      const notesCard = U.card('Tagesjournal', `<textarea class="input note-body" id="day-notes" data-input="day-notes" data-day="${key}" style="min-height:160px" placeholder="Wie lief der Tag? Was nimmst du mit?">${esc(d.notes || '')}</textarea><div class="small faint">Wird automatisch gespeichert.</div>`);
      return `${nav}${stats}<div class="grid main-side">${tradesCard}<div class="stack" style="gap:18px">${checkCard}${rulesCard}</div></div><div class="grid two">${notesCard}${regimeCard}</div>`;
    },
  };
  Object.assign(App.actions, {
    'new-trade-day'(el) { const d = C.parseDayKey(el.dataset.day); d.setHours(9, 0, 0, 0); App.openTradeEditor(null, { openedAt: d.toISOString() }); },
    'day-regime'(el) { const d = S.day(el.dataset.day) || {}; const reg = Object.assign({}, d.regime || {}); reg[el.dataset.kind] = reg[el.dataset.kind] === el.dataset.value ? undefined : el.dataset.value; S.setDay(el.dataset.day, { regime: reg }); App.rerender(); },
    'day-rule'(el) { const d = S.day(el.dataset.day) || {}; const set = new Set(d.rulesFollowed || []); set.has(el.dataset.rule) ? set.delete(el.dataset.rule) : set.add(el.dataset.rule); S.setDay(el.dataset.day, { rulesFollowed: [...set] }); App.rerender(); },
    'day-notes'(el) { clearTimeout(App._dn); App._dn = setTimeout(() => S.setDay(el.dataset.day, { notes: el.value }), 400); },
  });
})(typeof self !== 'undefined' ? self : this);
