/* Coach, Zen-Modus, Einstellungen */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;

  /* ---------- Coach ---------- */
  App.screens.coach = {
    title: 'Coach',
    render(ctx) {
      const list = ctx.inRange; const ins = C.insights({ trades: list, account: App.account(), regimeByDay: S.regimeByDay(), checkInByDay: S.checkInByDay(), currency: S.currency() === 'EUR' ? '€' : S.currency() });
      const icon = { good: 'trend', warn: 'warning', loss: 'warning', info: 'sparkle' };
      const today = App.todayTrades(ctx.all); const tilt = C.tiltCheck(today, { account: App.account(), dailyLossLimitPct: S.settings.dailyLossLimitPct / 100 });
      return `<div class="row between"><p class="muted" style="max-width:640px">Regelbasierte Einsichten aus deinen Daten im gewählten Zeitraum. Keine externe KI, alles wird lokal im Browser berechnet.</p></div>
        ${tilt.warnings.length ? `<div class="stack">${tilt.warnings.map(w => U.banner(w.severity === 'critical' ? 'loss' : 'warn', w.title, w.text)).join('')}</div>` : ''}
        <div class="grid two">${ins.map(i => `<div class="insight ${i.kind}"><div class="ico">${I[icon[i.kind] || 'sparkle']}</div><div class="grow"><b>${esc(i.title)}</b><p>${esc(i.text)}</p>${i.link ? `<a class="btn xs ghost" href="${i.link}" style="margin-top:8px">Details ${I.chevR}</a>` : ''}</div></div>`).join('')}</div>`;
    },
  };

  /* ---------- Zen-Modus ---------- */
  App.screens.zen = {
    title: 'Zen-Modus',
    render(ctx) {
      const rules = S.data.rules.filter(r => r.active !== false); const sess = S.activeSession(); const todayKey = C.dayKey(new Date()); const today = S.day(todayKey) || {}; const n = App.todayTrades(ctx.all).length;
      return `<div class="zen"><div><div class="caption">${fmt.weekdayLong(new Date())}</div><div class="clock" id="zen-clock">${new Date().toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}</div><div class="timer" id="zen-timer">${sess ? 'Session ' + fmt.hm((Date.now() - new Date(sess.startedAt)) / 1000) : 'Keine Session aktiv'}</div>
        <p class="muted" style="margin-top:14px">${n ? `${n} Trade${n === 1 ? '' : 's'} heute.` : 'Noch kein Trade heute.'} Der Kontostand bleibt hier bewusst verborgen.</p>
        ${today.checkIn && today.checkIn.goal ? `<p style="margin-top:10px"><span class="muted">Fokus:</span> <b>${esc(today.checkIn.goal)}</b></p>` : ''}
        <div class="row" style="justify-content:center;margin-top:20px">${sess ? `<button type="button" class="btn" data-action="end-session">${I.stop} Session beenden</button>` : `<button type="button" class="btn primary" data-action="start-session">${I.play} Session starten</button>`}<button type="button" class="btn accent" data-action="new-trade">${I.plus} Trade loggen</button></div>
        ${rules.length ? `<div class="rules card"><div class="caption" style="margin-bottom:8px">Deine Regeln</div>${rules.map(r => `<div class="comp"><span>${esc(r.text)}</span></div>`).join('')}</div>` : ''}
        </div></div>`;
    },
    mount() { App.stopZenTimer(); App.state.zenTimer = setInterval(() => { const c = document.getElementById('zen-clock'); if (c) c.textContent = new Date().toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' }); const s = S.activeSession(); const t = document.getElementById('zen-timer'); if (t && s) t.textContent = 'Session ' + fmt.hm((Date.now() - new Date(s.startedAt)) / 1000); }, 1000); },
  };

  /* ---------- Einstellungen ---------- */
  App.screens.settings = {
    title: 'Einstellungen',
    render() {
      const st = S.settings; const acc = S.data.accounts; const tags = S.data.tags; const rules = S.data.rules;
      const general = U.card('Allgemein', `<form data-action="save-settings" class="stack"><div class="form-grid"><div class="field"><label for="se-name">Dein Name</label><input class="input" id="se-name" name="name" value="${esc(st.name || '')}"></div><div class="field"><label for="se-cur">Währung (Standard)</label><select class="select" id="se-cur" name="currency">${['EUR', 'USD', 'CHF', 'GBP'].map(c => `<option ${st.currency === c ? 'selected' : ''}>${c}</option>`).join('')}</select></div><div class="field"><label for="se-loss">Tagesverlustlimit (% vom Konto)</label><input class="input" type="number" step="0.5" min="0" id="se-loss" name="dailyLossLimitPct" value="${st.dailyLossLimitPct}" inputmode="decimal"></div><div class="field"><label for="se-ruin">Ruin-Schwelle Monte Carlo (% Drawdown)</label><input class="input" type="number" step="5" min="5" max="95" id="se-ruin" name="ruinDrawdownPct" value="${st.ruinDrawdownPct}" inputmode="decimal"></div><div class="field"><label for="se-runs">Monte-Carlo-Durchläufe</label><select class="select" id="se-runs" name="mcRuns">${[500, 1000, 2000, 5000].map(n => `<option ${st.mcRuns === n ? 'selected' : ''}>${n}</option>`).join('')}</select></div><div class="field"><span class="lbl">Tilt-Warnungen</span><label class="check"><input type="checkbox" name="tiltWarnings" ${st.tiltWarnings ? 'checked' : ''}> Warnungen auf dem Dashboard anzeigen</label></div></div><div class="row" style="justify-content:flex-end"><button type="submit" class="btn primary sm">Speichern</button></div></form>`);
      const accounts = U.card('Konten', `<div class="tbl-wrap inset"><table class="tbl compact" style="min-width:0"><thead><tr><th>Name</th><th class="r">Kontogröße</th><th>Währung</th><th class="r">Trades</th><th></th></tr></thead><tbody>${acc.map(a => `<tr><td>${esc(a.name)}</td><td class="r">${fmt.num(a.size, 0)}</td><td>${esc(a.currency || st.currency)}</td><td class="r">${S.trades().filter(t => t.accountId === a.id).length}</td><td class="r"><button type="button" class="btn ghost icon sm" data-action="edit-account" data-id="${a.id}" aria-label="Bearbeiten">${I.edit}</button>${acc.length > 1 ? `<button type="button" class="btn ghost icon sm" data-action="delete-account" data-id="${a.id}" aria-label="Löschen">${I.trash}</button>` : ''}</td></tr>`).join('')}</tbody></table></div><div style="margin-top:10px"><button type="button" class="btn sm" data-action="edit-account">${I.plus} Konto hinzufügen</button></div>`, { info: 'Die Kontogröße bestimmt Tageslimit, Score-Drawdown und Monte Carlo.' });
      const rulesCard = U.card('Handelsregeln', `<div class="stack" style="gap:6px">${rules.length ? rules.map(r => `<div class="row" style="padding:6px 0;border-bottom:1px solid var(--border)"><button type="button" class="switch" role="switch" aria-checked="${r.active !== false}" data-action="toggle-rule" data-id="${r.id}" aria-label="Aktiv"></button><span class="grow ${r.active === false ? 'muted' : ''}">${esc(r.text)}</span><button type="button" class="btn ghost icon sm" data-action="delete-rule" data-id="${r.id}" aria-label="Löschen">${I.trash}</button></div>`).join('') : '<div class="muted small">Noch keine Regeln.</div>'}</div><form data-action="add-rule" class="row" style="margin-top:12px"><input class="input grow" name="text" placeholder="Neue Regel, z. B. „Maximal 3 Trades pro Tag“" required aria-label="Neue Regel"><button type="submit" class="btn sm primary">${I.plus} Hinzufügen</button></form>`, { info: 'Regeln erscheinen im Trade-Editor, beim Session-Ende und im Fortschritt.' });
      const tagCard = kind => { const label = { setups: 'Setups', mistakes: 'Fehler-Tags', emotions: 'Emotionen' }[kind]; const cls = { setups: 'setup', mistakes: 'mistake', emotions: 'emotion' }[kind]; return `<div class="field"><span class="lbl">${label}</span><div class="chips">${tags[kind].map(t => `<span class="chip ${cls}">${esc(t)} <button type="button" class="btn ghost icon xs" style="padding:0;width:16px;height:16px;color:inherit" data-action="remove-tag" data-kind="${kind}" data-value="${esc(t)}" aria-label="Entfernen">${I.close}</button></span>`).join('')}</div><form data-action="add-tag" data-kind="${kind}" class="row" style="margin-top:6px"><input class="input" name="name" placeholder="Neu …" style="max-width:220px" aria-label="Neuer Tag"><button type="submit" class="btn xs">${I.plus}</button></form></div>`; };
      const tagsCard = U.card('Tags', `<div class="stack" style="gap:16px">${tagCard('setups')}${tagCard('mistakes')}${tagCard('emotions')}</div>`);
      const dataCard = U.card('Daten', `<div class="stack" style="gap:14px">
        <div class="row between" style="gap:12px"><div><b>Beispieldaten</b><div class="small muted">Rund 170 Trades über vier Monate mit Check-ins, Notizen, Strategien und Regeln. Jederzeit entfernbar.</div></div>${st.sampleInstalled ? `<button type="button" class="btn sm danger" data-action="remove-sample">Entfernen</button>` : `<button type="button" class="btn sm" data-action="install-sample">Laden</button>`}</div>
        <div class="divider"></div>
        <div class="row between" style="gap:12px"><div><b>Sicherung exportieren</b><div class="small muted">Alle Trades, Notizen und Einstellungen als JSON. Optional mit Bildern und Audio.</div></div><div class="row"><button type="button" class="btn sm" data-action="export" data-blobs="0">${I.download} Ohne Anhänge</button><button type="button" class="btn sm" data-action="export" data-blobs="1">${I.download} Mit Anhängen</button></div></div>
        <div class="row between" style="gap:12px"><div><b>Sicherung einspielen</b><div class="small muted">JSON-Datei aus einem Export. „Zusammenführen“ behält vorhandene Daten.</div></div><div class="row"><button type="button" class="btn sm" data-action="import-backup" data-mode="merge">${I.upload} Zusammenführen</button><button type="button" class="btn sm" data-action="import-backup" data-mode="replace">${I.upload} Ersetzen</button><input type="file" id="backup-file" accept="application/json,.json" class="hidden"></div></div>
        <div class="row between" style="gap:12px"><div><b>CSV importieren</b><div class="small muted">Trades aus Broker-Exporten mit Spaltenzuordnung.</div></div><button type="button" class="btn sm" data-action="import">${I.csv} CSV</button></div>
        <div class="divider"></div>
        <div class="row between" style="gap:12px"><div><b class="neg">Alles löschen</b><div class="small muted">Entfernt alle Daten aus diesem Browser. Vorher exportieren!</div></div><button type="button" class="btn sm danger" data-action="wipe">${I.trash} Alles löschen</button></div>
        <div class="small faint">Speicherort: dieser Browser (localStorage und IndexedDB). ${S.storageOK ? '' : '<span class="neg">Achtung: Speichern ist derzeit nicht möglich (privates Fenster oder blockierte Website-Daten).</span>'}</div></div>`);
      const about = U.card('Über', `<p class="small muted">Trading Journal, Web-Version. Aufbau und Optik orientieren sich an TradeZella und TradePath. Alle Auswertungen laufen lokal im Browser, es werden keine Daten übertragen.</p><div class="divider"></div><div class="small muted">Tastatur: <b>N</b> neuer Trade · <b>1–8</b> Bereiche · <b>Esc</b> schließt Dialoge</div>`);
      return `<div class="grid two">${general}${accounts}${rulesCard}${tagsCard}${dataCard}${about}</div>`;
    },
  };
  function accountEditor(a) {
    const s = a || { name: '', size: 10000, currency: S.settings.currency };
    U.modal(`<form data-action="save-account" data-id="${s.id || ''}"><div class="modal-head"><h2>${a ? 'Konto bearbeiten' : 'Konto hinzufügen'}</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><div class="form-grid"><div class="field"><label for="ac-name">Name</label><input class="input" id="ac-name" name="name" value="${esc(s.name)}" required></div><div class="field"><label for="ac-size">Kontogröße</label><input class="input" type="number" step="any" min="0" id="ac-size" name="size" value="${s.size}" required inputmode="decimal"></div><div class="field"><label for="ac-cur">Währung</label><select class="select" id="ac-cur" name="currency">${['EUR', 'USD', 'CHF', 'GBP'].map(c => `<option ${(s.currency || 'EUR') === c ? 'selected' : ''}>${c}</option>`).join('')}</select></div></div><div class="modal-foot"><button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`, { cls: 'narrow' });
  }
  function download(name, text) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([text], { type: 'application/json' })); a.download = name; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000); }
  Object.assign(App.actions, {
    'save-settings'(form) { const fd = new FormData(form); S.data.settings.name = String(fd.get('name') || '').trim() || 'Trader'; S.data.settings.currency = fd.get('currency'); S.data.settings.dailyLossLimitPct = Number(fd.get('dailyLossLimitPct')) || 0; S.data.settings.ruinDrawdownPct = Number(fd.get('ruinDrawdownPct')) || 30; S.data.settings.mcRuns = Number(fd.get('mcRuns')) || 1000; S.data.settings.tiltWarnings = fd.get('tiltWarnings') === 'on'; S.save(); U.toast('Gespeichert', 'ok'); App.rerender(); },
    'edit-account'(el) { accountEditor(el.dataset.id ? S.data.accounts.find(a => a.id === el.dataset.id) : null); },
    'save-account'(form) { const fd = new FormData(form); const patch = { name: String(fd.get('name')).trim(), size: Number(fd.get('size')) || 0, currency: fd.get('currency') }; if (form.dataset.id) S.updateAccount(form.dataset.id, patch); else S.addAccount(patch); U.closeModal(); App.rerender(); },
    async 'delete-account'(el) { if (await U.confirmModal('Konto löschen?', 'Trades dieses Kontos werden dem ersten verbleibenden Konto zugeordnet.', { ok: 'Löschen', danger: true })) { S.deleteAccount(el.dataset.id); App.rerender(); } },
    'add-rule'(form) { const t = String(new FormData(form).get('text') || '').trim(); if (t) S.addRule(t); App.rerender(); },
    'toggle-rule'(el) { const r = S.data.rules.find(x => x.id === el.dataset.id); if (r) S.updateRule(r.id, { active: r.active === false }); App.rerender(); },
    'delete-rule'(el) { S.deleteRule(el.dataset.id); App.rerender(); },
    'add-tag'(form) { const n = String(new FormData(form).get('name') || '').trim(); if (n) S.addTag(form.dataset.kind, n); App.rerender(); },
    'remove-tag'(el) { S.removeTag(el.dataset.kind, el.dataset.value); App.rerender(); },
    async export(el) { const withBlobs = el.dataset.blobs === '1'; U.toast('Sicherung wird erstellt …'); const text = await S.exportJSON(withBlobs); const name = `trading-journal-${C.dayKey(new Date())}.json`; download(name, text); U.modal(`<div class="modal-head"><h2>Sicherung erstellt</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><p class="muted small">Falls der Download nicht startet (z. B. in einer eingebetteten Ansicht), kopiere den Text und speichere ihn als <b>${name}</b>.</p><textarea class="input mono" id="export-text" style="min-height:160px" readonly>${esc(text.length > 2_000_000 ? 'Zu groß für die Anzeige. Nutze den Download.' : text)}</textarea><div class="modal-foot"><button type="button" class="btn" data-action="copy-export">${I.copy} Kopieren</button><button type="button" class="btn primary" data-close>Fertig</button></div>`); },
    async 'copy-export'() { const ta = document.getElementById('export-text'); try { await navigator.clipboard.writeText(ta.value); U.toast('Kopiert', 'ok'); } catch (e) { ta.select(); U.toast('Text markiert, jetzt mit Strg+C kopieren'); } },
    'import-backup'(el) { const mode = el.dataset.mode; U.modal(`<div class="modal-head"><h2>Sicherung ${mode === 'merge' ? 'zusammenführen' : 'ersetzen'}</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div>${mode === 'replace' ? `<div class="banner warn">${I.warning}<div>Alle vorhandenen Daten werden durch die Sicherung ersetzt.</div></div>` : ''}<div class="dropzone" id="bk-drop">${I.upload}<div>JSON-Datei hierher ziehen oder klicken</div><input type="file" id="bk-file" accept="application/json,.json" class="hidden"></div><details><summary class="muted small" style="cursor:pointer">Oder Text einfügen</summary><textarea class="input mono" id="bk-text" style="min-height:120px"></textarea><button type="button" class="btn sm" id="bk-go" style="margin-top:8px">Einspielen</button></details>`, { cls: 'narrow', onMount(m) { const run = async text => { try { const r = await S.importJSON(text, mode); U.closeModal(); U.toast(`Sicherung eingespielt (${r.trades} Trades)`, 'ok'); App.rerender(false); } catch (e) { U.toast('Datei nicht lesbar: ' + e.message, 'err'); } }; const dz = m.querySelector('#bk-drop'), fi = m.querySelector('#bk-file'); const rf = f => { const r = new FileReader(); r.onload = () => run(r.result); r.readAsText(f); }; dz.addEventListener('click', () => fi.click()); fi.addEventListener('change', () => fi.files[0] && rf(fi.files[0])); dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('over'); }); dz.addEventListener('dragleave', () => dz.classList.remove('over')); dz.addEventListener('drop', e => { e.preventDefault(); dz.classList.remove('over'); e.dataTransfer.files[0] && rf(e.dataTransfer.files[0]); }); m.querySelector('#bk-go').addEventListener('click', () => run(m.querySelector('#bk-text').value)); } }); },
    async wipe() { if (await U.confirmModal('Wirklich alles löschen?', 'Alle Trades, Notizen, Bilder und Einstellungen in diesem Browser werden entfernt. Das lässt sich nicht rückgängig machen.', { ok: 'Alles löschen', danger: true })) { await S.wipe(); U.toast('Alle Daten gelöscht'); App.navigate('#/dashboard'); App.rerender(false); } },
  });
})(typeof self !== 'undefined' ? self : this);
