/* Notebook: Ordner, Notizliste, Notiz mit Editor, Tags, Vorlagen, Papierkorb, Teilen */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;
  const FOLDER_COLORS = ['#34f58a', '#5cb8ff', '#f5b93a', '#8b7cf6', '#ff5c5c', '#f97316', '#ec4899', '#22d3ee', '#9aa3a0'];
  const st = () => App.state.nb || (App.state.nb = { folder: 'all', note: null, q: '', tag: null, filter: { folder: '', tag: '', from: '', to: '' }, sort: 'updated', selected: [], selectMode: false, leftOpen: true, foldersOpen: true, tagsOpen: true, focus: false, statsOpen: false, view: 'list' });
  let editor = null, saveTimer = null, pendingContent = null, pendingId = null;

  function visibleNotes() {
    const nb = st(); const q = nb.q.trim().toLowerCase(); const f = nb.filter;
    let list = S.notes({ trash: nb.folder === 'trash' });
    if (nb.folder !== 'all' && nb.folder !== 'trash' && !q) list = list.filter(n => n.folderId === nb.folder);
    if (f.folder) list = list.filter(n => n.folderId === f.folder);
    const tag = nb.tag || f.tag; if (tag) list = list.filter(n => (n.tags || []).includes(tag));
    if (f.from) list = list.filter(n => (n.updatedAt || '') >= f.from); if (f.to) list = list.filter(n => (n.updatedAt || '').slice(0, 10) <= f.to);
    if (q) list = list.filter(n => (n.title || '').toLowerCase().includes(q) || S.deltaText(n.content).toLowerCase().includes(q));
    const key = { updated: (a, b) => (b.updatedAt || '').localeCompare(a.updatedAt || ''), newest: (a, b) => (b.createdAt || '').localeCompare(a.createdAt || ''), oldest: (a, b) => (a.createdAt || '').localeCompare(b.createdAt || ''), title: (a, b) => (a.title || '').localeCompare(b.title || '', 'de') }[nb.sort];
    return list.sort(key);
  }
  const folderIcon = f => f.id === 'daily' ? I.calendar : f.id === 'trades' ? I.tradelog : f.id === 'recap' ? I.note : I.folder;
  function linkedTrades(n) { if (!n.dateKey && !n.tradeId) return []; const all = App.allTrades(); if (n.type === 'trade' && n.tradeId) { const t = all.find(x => x.id === n.tradeId); return t ? [t] : []; } return all.filter(t => t.dayKey === n.dateKey); }
  function notePnL(n) { const ts = linkedTrades(n).filter(t => t.closed); return ts.length ? C.sum(ts.map(t => t.pnl)) : null; }

  /* Tag-Menü: Inhalte-Tags (Setups, Fehler, Emotionen) plus eigene Notiz-Tags, Haken für zugewiesene */
  function tagMenuHTML(cur) {
    const assigned = new Set(cur.tags || []); const nt = S.noteTags(); const byName = n => nt.find(t => t.name.toLowerCase() === n.toLowerCase()); const used = new Set();
    const item = n => { const t = byName(n); const on = !!(t && assigned.has(t.id)); used.add(n.toLowerCase()); return `<button type="button" class="item" data-action="nb-tag-toggle" data-id="${cur.id}" data-name="${esc(n)}" aria-checked="${on}"><span class="chk">${on ? I.check : ''}</span>${esc(n)}</button>`; };
    const tags = S.data.tags || {}; const cols = [['Setups', tags.setups || []], ['Fehler', tags.mistakes || []], ['Emotionen', tags.emotions || []]].filter(([, names]) => names.length).map(([label, names]) => `<div class="tagcol"><div class="sec">${label}</div>${names.map(item).join('')}</div>`);
    const own = nt.filter(t => !used.has(t.name.toLowerCase())).sort((a, b) => a.name.localeCompare(b.name, 'de')); if (own.length) cols.push(`<div class="tagcol"><div class="sec">Eigene</div>${own.map(t => item(t.name)).join('')}</div>`);
    return cols.length ? `<div class="tagcols">${cols.join('')}</div>` : '<div class="small muted" style="padding:8px 12px">Noch keine Tags</div>';
  }
  App.screens.notebook = {
    title: 'Notebook',
    render(ctx) {
      const nb = st();
      if (ctx.params[0] && ctx.params[0] !== nb._lastParam) { nb._lastParam = ctx.params[0]; const n = S.getNote(ctx.params[0]); if (n) { nb.note = n.id; if (n.deletedAt) nb.folder = 'trash'; else if (nb.folder !== 'all' && nb.folder !== n.folderId) nb.folder = n.folderId; nb.view = 'note'; } }
      const notes = visibleNotes(); let cur = nb.note ? notes.find(n => n.id === nb.note) || S.getNote(nb.note) : null; if (cur && cur.deletedAt && nb.folder !== 'trash') cur = null; if (!cur && notes.length && nb.folder !== 'trash') cur = notes[0]; nb.note = cur ? cur.id : null;
      nb.selected = nb.selected.filter(id => notes.some(n => n.id === id));
      const folders = S.folders(); const tags = S.tagCounts(); const f = nb.filter; const activeFilters = [f.folder && `Ordner: ${(S.getFolder(f.folder) || {}).name || ''}`, f.tag && `Tag: ${(S.noteTags().find(t => t.id === f.tag) || {}).name || ''}`, (f.from || f.to) && `Zeitraum: ${f.from ? fmt.dateFull(f.from) : '…'} – ${f.to ? fmt.dateFull(f.to) : '…'}`].filter(Boolean);
      const search = `<div class="nb-search"><div class="q">${I.search}<input class="input" id="nb-q" data-input="nb-q" value="${esc(nb.q)}" placeholder="Notizen durchsuchen" aria-label="Notizen durchsuchen"></div>
        <div class="popwrap"><button type="button" class="btn icon" data-pop="nbfilter" aria-label="Filter" data-tip="Filtern nach Ordner, Tag und Zeitraum">${I.filter}${activeFilters.length ? `<span class="badge l" style="margin-left:4px">${activeFilters.length}</span>` : ''}</button><div class="popover" id="pop-nbfilter" style="min-width:280px"><form class="range-form" data-action="nb-filter"><div class="field"><label class="lbl" for="nbf-folder">Ordner</label><select class="select" id="nbf-folder" name="folder"><option value="">Alle</option>${folders.map(x => `<option value="${x.id}" ${f.folder === x.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label class="lbl" for="nbf-tag">Tag</label><select class="select" id="nbf-tag" name="tag"><option value="">Alle</option>${tags.map(t => `<option value="${t.id}" ${f.tag === t.id ? 'selected' : ''}>${esc(t.name)}</option>`).join('')}</select></div><div class="row" style="gap:6px"><input class="input" type="date" name="from" value="${esc(f.from || '')}" aria-label="Von"><input class="input" type="date" name="to" value="${esc(f.to || '')}" aria-label="Bis"></div><div class="row" style="justify-content:flex-end"><button type="button" class="btn sm ghost" data-action="nb-filter-reset">Zurücksetzen</button><button type="submit" class="btn sm primary">Anwenden</button></div></form></div></div>
        ${activeFilters.length ? `<div class="nb-chips">${activeFilters.map(x => `<span class="chip">${esc(x)}</span>`).join('')}<button type="button" class="btn xs ghost" data-action="nb-filter-reset">${I.close} Filter aufheben</button></div>` : ''}</div>`;
      /* Linke Spalte */
      const counts = {}; for (const n of S.notes()) counts[n.folderId] = (counts[n.folderId] || 0) + 1; const total = S.notes().length; const trashN = S.notes({ trash: true }).length;
      const folderRow = x => `<div class="folder ${nb.folder === x.id ? 'active' : ''}" style="border-left-color:${x.isDefault ? 'transparent' : esc(x.color)}" data-action="nb-folder" data-id="${x.id}" role="button" tabindex="0">${x.isDefault ? folderIcon(x).replace('<svg', '<svg class="ico"') : ''}<span class="grow" style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(x.name)}</span><span class="popwrap" data-stop><button type="button" class="btn ghost icon sm more" data-pop="fm-${x.id}" aria-label="Ordnermenü">${I.more}</button><div class="popover" id="pop-fm-${x.id}"><button type="button" class="item" data-action="nb-folder-edit" data-id="${x.id}">${I.edit} Umbenennen</button><button type="button" class="item" data-action="nb-folder-edit" data-id="${x.id}" data-color="1">${I.dot} Farbe ändern</button><button type="button" class="item" data-action="nb-folder-template" data-id="${x.id}">${I.note} Standard-Vorlage</button>${x.isDefault ? '' : `<hr><button type="button" class="item" data-action="nb-folder-delete" data-id="${x.id}"><span class="neg" style="display:inline-flex;gap:10px;align-items:center">${I.trash} Löschen</span></button>`}</div></span></div>`;
      const left = `<div class="col left"><div class="col-head"><button type="button" class="btn sm grow" data-action="nb-folder-add">${I.folder} Ordner hinzufügen</button><button type="button" class="btn ghost icon sm collapse-left" data-action="nb-left-toggle" aria-label="Spalte einklappen" data-tip="Spalte einklappen">${I.chevL}</button></div><div class="col-body">
        <button type="button" class="sec-h" data-action="nb-sec" data-key="foldersOpen" aria-expanded="${nb.foldersOpen}">${I.chev}<span>Ordner</span></button>
        ${nb.foldersOpen ? `<div class="folder ${nb.folder === 'all' ? 'active' : ''}" data-action="nb-folder" data-id="all" role="button" tabindex="0">${I.library.replace('<svg', '<svg class="ico"')}<span class="grow">Alle Notizen</span><span class="sp"></span></div>${folders.filter(x => x.isDefault).map(folderRow).join('')}<div class="fsep"></div>${folders.filter(x => !x.isDefault).map(folderRow).join('') || '<div class="small faint" style="padding:4px 10px">Noch keine eigenen Ordner</div>'}` : ''}
        <button type="button" class="sec-h" data-action="nb-sec" data-key="tagsOpen" aria-expanded="${nb.tagsOpen}" style="margin-top:8px">${I.chev}<span>Tags</span></button>
        ${nb.tagsOpen ? `<div class="tagpills">${tags.length ? tags.map(t => `<button type="button" class="tagpill" data-action="nb-tag" data-id="${t.id}" aria-pressed="${nb.tag === t.id}">${esc(t.name)} <b>${t.n}</b></button>`).join('') : '<span class="small faint">Noch keine Tags</span>'}</div>` : ''}
        </div><div class="trash-link ${nb.folder === 'trash' ? 'active' : ''}" data-action="nb-folder" data-id="trash" role="button" tabindex="0">${I.trash}<span class="grow">Kürzlich gelöscht</span></div></div>`;
      /* Mittlere Spalte */
      const isDaily = nb.folder === 'daily'; const sortLabels = { updated: 'Zuletzt bearbeitet', newest: 'Neueste zuerst', oldest: 'Älteste zuerst', title: 'Titel A–Z' };
      const listItems = notes.map(n => { const t = n.type === 'trade' ? linkedTrades(n)[0] : null; const pnl = t ? (t.closed ? t.pnl : null) : null; const sel = nb.selected.includes(n.id); return `<div class="note-item ${cur && cur.id === n.id ? 'active' : ''} ${sel ? 'selected' : ''}" data-action="${nb.selectMode ? 'nb-select' : 'nb-open'}" data-id="${n.id}" role="${nb.selectMode ? 'checkbox' : 'button'}" ${nb.selectMode ? `aria-checked="${sel}"` : ''} tabindex="0">${nb.selectMode ? `<span class="sel ${sel ? 'on' : ''}">${I.check}</span>` : ''}<div class="t"><b data-nb-title="${n.id}">${esc(n.title || 'Ohne Titel')}</b><div class="d" data-nb-date="${n.id}">${n.deletedAt ? 'Gelöscht ' + fmt.dateTime(n.deletedAt) : fmt.dateTime(n.updatedAt || n.createdAt)}</div>${t ? `<div class="tr"><b style="display:inline">${esc(t.symbol)}</b>${pnl != null ? U.pnl(pnl) : '<span class="muted">offen</span>'}</div>` : ''}</div></div>`; }).join('');
      const mid = `<div class="col mid"><div class="col-head">${!nb.leftOpen ? `<button type="button" class="btn ghost icon sm" data-action="nb-left-toggle" aria-label="Ordner anzeigen" data-tip="Ordner anzeigen">${I.chevR}</button>` : ''}<button type="button" class="btn ghost icon sm back" data-action="nb-view" data-value="folders" aria-label="Zurück">${I.back}</button>${nb.folder === 'trash' ? `<span class="grow" style="font-weight:600">Papierkorb</span>${trashN ? `<button type="button" class="btn sm danger" data-action="nb-trash-empty">Leeren</button>` : ''}` : `<button type="button" class="btn sm primary grow" data-action="nb-new">${I.plus} ${isDaily ? 'Tag loggen' : 'Neue Notiz'}</button>`}${notes.length ? `<button type="button" class="btn ghost icon sm" data-action="nb-select-mode" aria-label="Notizen auswählen" data-tip="Notizen auswählen" aria-pressed="${nb.selectMode}">${I.check}</button>` : ''}<div class="popwrap"><button type="button" class="btn ghost icon sm" data-pop="nbsort" aria-label="Sortieren" data-tip="Sortieren: ${esc(sortLabels[nb.sort])}">${I.arrowDown}</button><div class="popover" id="pop-nbsort">${Object.entries(sortLabels).map(([k, l]) => `<button type="button" class="item" data-action="nb-sort" data-value="${k}" aria-checked="${nb.sort === k}">${l}</button>`).join('')}</div></div></div>
        ${notes.length && nb.selectMode ? `<div class="sel-row"><button type="button" class="btn xs ghost" data-action="nb-select-all">${nb.selected.length && nb.selected.length === notes.length ? 'Keine' : 'Alle'}</button><span class="cnt">${nb.selected.length ? nb.selected.length + ' gewählt' : 'Notizen antippen'}</span><span class="grow"></span>${nb.folder === 'trash' ? `<button type="button" class="btn xs" data-action="nb-trash-restore-sel" ${nb.selected.length ? '' : 'disabled'}>Wiederherstellen</button><button type="button" class="btn ghost icon sm danger" data-action="nb-trash-purge-sel" aria-label="Endgültig löschen" data-tip="Endgültig löschen" ${nb.selected.length ? '' : 'disabled'}>${I.trash}</button>` : `<div class="popwrap"><button type="button" class="btn ghost icon sm" data-pop="nbmove" aria-label="Verschieben" data-tip="In Ordner verschieben" ${nb.selected.length ? '' : 'disabled'}>${I.folder}</button><div class="popover" id="pop-nbmove">${folders.map(x => `<button type="button" class="item" data-action="nb-move-sel" data-id="${x.id}"><i style="width:10px;height:10px;border-radius:3px;background:${esc(x.color)}"></i>${esc(x.name)}</button>`).join('')}</div></div><button type="button" class="btn ghost icon sm danger" data-action="nb-delete-sel" aria-label="Löschen" data-tip="Löschen" ${nb.selected.length ? '' : 'disabled'}>${I.trash}</button>`}<button type="button" class="btn xs" data-action="nb-select-mode">Fertig</button></div>` : ''}
        <div class="col-body" style="padding-top:6px">${notes.length ? listItems : U.empty(nb.folder === 'trash' ? 'trash' : 'note', nb.folder === 'trash' ? 'Papierkorb ist leer' : nb.q || activeFilters.length || nb.tag ? 'Keine Notizen gefunden' : 'Noch keine Notizen', nb.folder === 'trash' ? 'Gelöschte Notizen bleiben 30 Tage hier.' : nb.q ? 'Andere Suchbegriffe probieren.' : `Lege mit „${isDaily ? 'Tag loggen' : 'Neue Notiz'}“ los.`)}${nb.q && nb.folder !== 'all' && nb.folder !== 'trash' ? `<div class="small muted" style="padding:6px 12px;border-top:1px solid var(--border)">Suche über alle Ordner</div>` : ''}</div></div>`;
      /* Rechte Spalte */
      let right;
      if (!cur) right = `<div class="col right">${U.empty('journal', nb.folder === 'trash' ? 'Keine Notiz ausgewählt' : 'Keine Notiz geöffnet', nb.folder === 'trash' ? 'Wähle eine gelöschte Notiz, um sie wiederherzustellen.' : 'Wähle links eine Notiz oder lege eine neue an.', nb.folder === 'trash' ? '' : `<button type="button" class="btn sm primary" data-action="nb-new">${I.plus} Neue Notiz</button>`)}</div>`;
      else if (cur.deletedAt) right = `<div class="col right"><div class="note-head"><div class="row"><button type="button" class="btn ghost icon sm back" data-action="nb-view" data-value="list" aria-label="Zurück">${I.back}</button><h2 style="font-size:20px" class="grow">${esc(cur.title || 'Ohne Titel')}</h2><button type="button" class="btn sm primary" data-action="nb-trash-restore" data-id="${cur.id}">Wiederherstellen</button><button type="button" class="btn sm danger" data-action="nb-trash-purge" data-id="${cur.id}">Endgültig löschen</button></div><div class="meta"><span>Gelöscht: ${fmt.dateTime(cur.deletedAt)}</span><span>Wird endgültig entfernt am ${fmt.dateFull(new Date(new Date(cur.deletedAt).getTime() + 30 * 86400000))}</span></div></div><div class="note-body nb-share-view"><div class="ql-container ql-snow"><div class="ql-editor">${root.NoteEditor ? root.NoteEditor.toHTML(cur.content) : esc(S.deltaText(cur.content))}</div></div></div></div>`;
      else {
        const linked = cur.type === 'day' || cur.type === 'trade' ? linkedTrades(cur) : []; const pnl = linked.filter(t => t.closed).length ? C.sum(linked.filter(t => t.closed).map(t => t.pnl)) : null; const folder = S.getFolder(cur.folderId); const noteTags = (cur.tags || []).map(id => S.noteTags().find(t => t.id === id)).filter(Boolean);
        const dateKey = cur.dateKey || C.dayKey(new Date(cur.createdAt)); const canPick = cur.type !== 'trade';
        const stats = linked.length ? statsHTML(cur, linked, nb.statsOpen) : '';
        right = `<div class="col right"><div class="note-head">
          <div class="row" style="justify-content:space-between;flex-wrap:nowrap"><div class="row"><button type="button" class="btn ghost icon sm back" data-action="nb-view" data-value="list" aria-label="Zurück">${I.back}</button><div class="popwrap"><button type="button" class="datebtn" ${canPick ? `data-pop="nbdate"` : 'disabled'} data-tip="${canPick ? 'Datum der Notiz ändern' : 'Datum des Trades'}">${I.calendar}<span>${esc(S.dayTitle(dateKey))}</span>${canPick ? I.chev : ''}</button>${canPick ? `<div class="popover left" id="pop-nbdate">${datePickerHTML(cur, dateKey)}</div>` : ''}</div></div>
          <div class="row" style="gap:6px;flex-wrap:nowrap"><span class="save-state" id="nb-save">Gespeichert</span><button type="button" class="btn ghost sm" data-action="nb-share" data-id="${cur.id}" data-tip="Nur-Lese-Link erzeugen">${I.external}<span class="hide-m">Teilen</span></button><div class="popwrap"><button type="button" class="btn ghost icon sm" data-pop="nbmenu" aria-label="Mehr">${I.more}</button><div class="popover" id="pop-nbmenu"><div class="sec">In Ordner verschieben</div>${folders.map(x => `<button type="button" class="item" data-action="nb-move" data-id="${cur.id}" data-folder="${x.id}" aria-checked="${cur.folderId === x.id}"><i style="width:10px;height:10px;border-radius:3px;background:${esc(x.color)}"></i>${esc(x.name)}</button>`).join('')}<hr><button type="button" class="item" data-action="nb-duplicate" data-id="${cur.id}">${I.copy} Duplizieren</button><button type="button" class="item" data-action="nb-import" data-id="${cur.id}">${I.upload} Aus Datei laden</button><button type="button" class="item" data-action="nb-export" data-id="${cur.id}">${I.download} Exportieren (JSON)</button><button type="button" class="item" data-action="nb-pdf">${I.download} Als PDF herunterladen</button><hr><button type="button" class="item" data-action="nb-delete" data-id="${cur.id}"><span class="neg" style="display:inline-flex;gap:10px;align-items:center">${I.trash} Löschen</span></button></div></div></div></div>
          <input class="note-title" id="nb-title" value="${esc(cur.title || '')}" placeholder="Neue Notiz" data-input="nb-title" data-id="${cur.id}" aria-label="Titel">
          <div class="meta"><div>Erstellt: ${fmt.dateTime(cur.createdAt)}</div><div id="nb-updated">Zuletzt bearbeitet: ${fmt.dateTime(cur.updatedAt || cur.createdAt)}</div>${pnl != null ? `<div style="margin-top:4px;font-weight:700;color:var(--text)">Netto-P&L ${U.pnl(pnl)}${cur.type === 'trade' && linked[0] ? ` <span class="muted small" style="font-weight:500">· ${esc(linked[0].symbol)} ${linked[0].direction > 0 ? 'Long' : 'Short'} · <a href="#/trades/${linked[0].id}" class="accent">Trade öffnen</a></span>` : ` <span class="muted small" style="font-weight:500">· <a href="#/day/${dateKey}" class="accent">Tagesansicht</a></span>`}</div>` : ''}</div>
          <div class="tags-row">${noteTags.map(t => `<span class="chip setup">${esc(t.name)}<button type="button" data-action="nb-tag-remove" data-id="${cur.id}" data-tag="${t.id}" aria-label="Tag entfernen">${I.close}</button></span>`).join('')}<div class="popwrap"><button type="button" class="tag-add" data-pop="nbtags" aria-label="Tag hinzufügen">${I.plus} Tag</button><div class="popover left tagpop" id="pop-nbtags">${tagMenuHTML(cur)}<hr><button type="button" class="item" data-action="nb-tag-new" data-id="${cur.id}">${I.plus} Neuen Tag anlegen</button></div></div></div>
          </div>${stats}<div class="note-body"><div id="nb-editor"></div><input type="file" accept="application/json,.json" class="hidden" id="nb-import-file"></div></div>`;
      }
      return `${search}<div class="nb ${nb.leftOpen ? '' : 'no-left'}" data-view="${nb.view}">${(nb.leftOpen ? left : '') + mid}${right}</div>`;
    },
    mount(main) {
      const nb = st(); const el = main.querySelector('#nb-editor'); if (!el || !root.NoteEditor) return; const n = S.getNote(nb.note); if (!n) return;
      editor = root.NoteEditor.create(el, { content: n.content, templates: () => S.templates().map(t => ({ id: t.id, name: t.name })), customColors: () => S.settings.editorColors || [],
        onChange(delta) { pendingContent = delta; pendingId = n.id; setSaveState('saving'); clearTimeout(saveTimer); saveTimer = setTimeout(flush, 1000); },
        onTemplate(id) { const t = S.getTemplate(id); if (!t || !editor) return; editor.insertDelta(JSON.parse(JSON.stringify(t.content))); S.markTemplateUsed(t.id); U.toast(`Vorlage „${t.name}“ eingefügt`, 'ok'); },
        onNewTemplate() { templateModal(null); }, onEditTemplate(id) { templateModal(S.getTemplate(id)); },
        onCustomColor(c) { const list = (S.settings.editorColors || []).filter(x => x !== c); list.unshift(c); S.setSetting('editorColors', list.slice(0, 10)); } });
      const imp = main.querySelector('#nb-import-file'); if (imp) imp.addEventListener('change', e => { const f = e.target.files[0]; if (!f || !editor) return; const r = new FileReader(); r.onload = () => { try { const j = JSON.parse(r.result); const delta = j.ops ? j : j.note && j.note.content ? j.note.content : j.content; if (!delta || !delta.ops) throw new Error('Kein Notiz-Format'); editor.setContents(delta); pendingContent = delta; pendingId = n.id; flush(); if (j.note && j.note.title) { S.updateNote(n.id, { title: j.note.title }); const t = main.querySelector('#nb-title'); if (t) t.value = j.note.title; } U.toast('Notiz geladen', 'ok'); } catch (err) { U.toast('Datei nicht lesbar: ' + err.message, 'err'); } }; r.readAsText(f); e.target.value = ''; });
      if (nb._openPop) { const pop = document.getElementById('pop-' + nb._openPop); if (pop) pop.classList.add('open'); nb._openPop = null; }
      const q = main.querySelector('#nb-q'); if (nb._focusSearch && q) { q.focus(); q.setSelectionRange(q.value.length, q.value.length); nb._focusSearch = false; }
    },
    unmount() { flush(); if (editor) { editor.destroy(); editor = null; } },
  };
  function setSaveState(s) { const el = document.getElementById('nb-save'); if (!el) return; el.textContent = s === 'saving' ? 'Speichert…' : 'Gespeichert'; el.classList.toggle('saving', s === 'saving'); }
  function flush() { clearTimeout(saveTimer); if (pendingContent && pendingId) { const n = S.updateNote(pendingId, { content: pendingContent }); pendingContent = null; if (n) { const d = document.querySelector(`[data-nb-date="${n.id}"]`); if (d) d.textContent = fmt.dateTime(n.updatedAt); const u = document.getElementById('nb-updated'); if (u) u.textContent = 'Zuletzt bearbeitet: ' + fmt.dateTime(n.updatedAt); } setSaveState('saved'); } }
  function statsHTML(n, trades, open) {
    const closed = trades.filter(t => t.closed).sort((a, b) => a.close - b.close); const s = C.summary(trades); let c = 0; const id = 'nb-spark-' + n.id; U.chartData[id] = { values: closed.map(t => (c += t.pnl)) };
    return `<div class="stats-box"><button type="button" class="sec-h" data-action="nb-stats" aria-expanded="${open}" style="padding:0 0 ${open ? '10px' : '0'}">${I.chev}<span>${n.type === 'trade' ? 'Trade-Statistik' : 'Tagesstatistik'} · ${trades.length} Trade${trades.length === 1 ? '' : 's'}</span></button>${open ? `<div class="stats-grid"><div class="chart h120" data-chart="spark" data-id="${id}"></div><div class="kpis"><div><div class="k">Trades</div><div class="v">${trades.length}</div></div><div><div class="k">Brutto-P&L</div><div class="v ${U.cls(s.gross)}">${fmt.cur(s.gross, { signed: true })}</div></div><div><div class="k">Gewinner / Verlierer</div><div class="v"><span class="pos">${s.wins}</span> / <span class="neg">${s.losses}</span></div></div><div><div class="k">Gebühren</div><div class="v">${fmt.cur(s.fees)}</div></div><div><div class="k">Trefferquote</div><div class="v">${closed.length ? fmt.pct(s.winRate) : '—'}</div></div><div><div class="k">Volumen</div><div class="v">${fmt.num(s.volume, 2)}</div></div><div><div class="k">Profit-Faktor</div><div class="v">${closed.length ? fmt.factor(s.pf) : '—'}</div></div></div></div>` : ''}</div>`;
  }
  function datePickerHTML(n, dateKey) {
    const nb = st(); const sel = C.parseDayKey(dateKey); const m = nb.pickMonth || new Date(sel.getFullYear(), sel.getMonth(), 1); nb.pickMonth = m;
    const first = new Date(m.getFullYear(), m.getMonth(), 1); const lead = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - lead); const today = C.dayKey(new Date());
    let cells = ''; for (let i = 0; i < 42; i++) { const d = new Date(start); d.setDate(start.getDate() + i); const k = C.dayKey(d); cells += `<button type="button" class="dp ${d.getMonth() !== m.getMonth() ? 'out' : ''} ${k === dateKey ? 'sel' : ''} ${k === today ? 'today' : ''}" data-action="nb-date-pick" data-id="${n.id}" data-key="${k}">${d.getDate()}</button>`; }
    return `<div class="datepick"><div class="row between"><button type="button" class="btn ghost icon sm" data-action="nb-date-nav" data-dir="-1" aria-label="Voriger Monat">${I.chevL}</button><b>${fmt.monthYear(m)}</b><button type="button" class="btn ghost icon sm" data-action="nb-date-nav" data-dir="1" aria-label="Nächster Monat">${I.chevR}</button></div><div class="grid7">${C.WEEKDAYS.map(w => `<span class="wd">${w}</span>`).join('')}${cells}</div></div>`;
  }
  function folderModal(f, colorOnly) {
    const cur = f || { name: '', color: FOLDER_COLORS[3] };
    U.modal(`<form data-action="nb-folder-save" data-id="${f ? f.id : ''}"><div class="modal-head"><h2>${f ? (colorOnly ? 'Farbe ändern' : 'Ordner bearbeiten') : 'Ordner hinzufügen'}</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><div class="stack"><div class="field"><label for="fo-name">Name</label><input class="input" id="fo-name" name="name" value="${esc(cur.name)}" placeholder="z. B. 📈 Strategie" required ${colorOnly ? 'readonly' : ''}></div><div class="field"><span class="lbl">Farbe</span><div class="swatches">${FOLDER_COLORS.map(c => `<button type="button" class="swatch" data-action="fo-color" data-value="${c}" aria-pressed="${cur.color === c}" aria-label="${c}"><i style="background:${c}"></i></button>`).join('')}<label class="color-field"><input type="color" name="custom" value="${cur.color}" aria-label="Eigene Farbe" data-input="fo-color-custom"><span class="small muted">eigene</span></label></div><input type="hidden" name="color" value="${cur.color}"></div></div><div class="modal-foot"><button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`, { cls: 'narrow' });
  }
  function templateModal(tpl) {
    U.modal(`<form data-action="nb-tpl-save" data-id="${tpl ? tpl.id : ''}"><div class="modal-head"><h2>${tpl ? 'Vorlage bearbeiten' : 'Vorlage hinzufügen'}</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><div class="field"><label for="tp-name">Name</label><input class="input" id="tp-name" name="name" value="${esc(tpl ? tpl.name : '')}" placeholder="z. B. Tages-Recap" required></div><div class="field"><span class="lbl">Inhalt</span><div id="tpl-editor" style="border:1px solid var(--border-2);border-radius:10px;padding:0 8px"></div></div><div class="modal-foot">${tpl ? `<button type="button" class="btn ghost left" data-action="nb-tpl-delete-cur" data-id="${tpl.id}">${I.trash} Vorlage löschen</button>` : ''}<button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`, { cls: 'wide', onMount(m) { m._tplEditor = root.NoteEditor.create(m.querySelector('#tpl-editor'), { content: tpl ? tpl.content : null, placeholder: 'Inhalt der Vorlage …', customColors: () => S.settings.editorColors || [] }); }, onClose() { } });
  }
  function shareToken(n) { const ops = (n.content && n.content.ops || []).map(o => (o.insert && typeof o.insert === 'object' && o.insert.figure) ? { insert: `[Bild${o.insert.figure.caption ? ': ' + o.insert.figure.caption : ''}]\n` } : o); const json = JSON.stringify({ t: n.title || '', c: { ops }, d: n.createdAt, u: n.updatedAt }); return btoa(unescape(encodeURIComponent(json))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); }
  function parseShare(tok) { try { const b = tok.replace(/-/g, '+').replace(/_/g, '/'); return JSON.parse(decodeURIComponent(escape(atob(b + '='.repeat((4 - b.length % 4) % 4))))); } catch (e) { return null; } }
  App.screens.share = { title: 'Geteilte Notiz', render(ctx) { const d = parseShare(ctx.params[0] || ''); if (!d || !d.c) return U.empty('note', 'Link ungültig', 'Diese geteilte Notiz konnte nicht gelesen werden.'); const safeOps = (d.c.ops || []).filter(o => typeof o.insert === 'string' || (o.insert && (o.insert.divider || o.insert.video || o.insert.details))); return `<section class="card nb-share-view" style="max-width:860px"><div class="row between"><h2 style="font-size:22px">${esc(d.t || 'Ohne Titel')}</h2>${U.pill('Nur lesen', 'neutral')}</div><div class="small muted" style="margin:4px 0 12px">Erstellt ${fmt.dateTime(d.d)} · Zuletzt bearbeitet ${fmt.dateTime(d.u)}</div><div class="ql-container ql-snow"><div class="ql-editor">${root.NoteEditor ? root.NoteEditor.toHTML({ ops: safeOps }) : ''}</div></div><div class="divider"></div><a class="btn sm" href="#/notebook">${I.journal} Zum eigenen Notebook</a></section>`; } };

  Object.assign(App.actions, {
    'nb-folder'(el) { const nb = st(); nb.folder = el.dataset.id; nb.note = null; nb.selected = []; nb.selectMode = false; nb.tag = null; nb.view = 'list'; nb._lastParam = null; history.replaceState(null, '', '#/notebook'); App.rerender(); },
    'nb-sec'(el) { const nb = st(); nb[el.dataset.key] = !nb[el.dataset.key]; App.rerender(); },
    'nb-tag'(el) { const nb = st(); nb.tag = nb.tag === el.dataset.id ? null : el.dataset.id; nb.note = null; App.rerender(); },
    'nb-left-toggle'() { const nb = st(); nb.leftOpen = !nb.leftOpen; App.rerender(); },
    'nb-view'(el) { st().view = el.dataset.value; App.rerender(); },
    'nb-q'(el) { const nb = st(); nb.q = el.value; nb._focusSearch = true; clearTimeout(App._nbq); App._nbq = setTimeout(() => App.rerender(), 250); },
    'nb-filter'(form) { const fd = new FormData(form); st().filter = { folder: fd.get('folder') || '', tag: fd.get('tag') || '', from: fd.get('from') || '', to: fd.get('to') || '' }; App.rerender(); },
    'nb-filter-reset'() { st().filter = { folder: '', tag: '', from: '', to: '' }; st().tag = null; App.rerender(); },
    'nb-sort'(el) { st().sort = el.dataset.value; App.rerender(); },
    'nb-open'(el) { const nb = st(); nb.note = el.dataset.id; nb.view = 'note'; nb._lastParam = nb.note; history.replaceState(null, '', '#/notebook/' + nb.note); App.rerender(); },
    'nb-new'() { const nb = st(); const folderId = nb.folder === 'all' || nb.folder === 'trash' ? 'daily' : nb.folder; let n; if (folderId === 'daily') { const key = C.dayKey(new Date()); n = S.dayNote(key) ? S.addNote({ folderId, type: 'day', dateKey: key, title: S.dayTitle(key) }) : S.dayNote(key, true); } else n = S.addNote({ folderId, title: '' }); nb.folder = folderId === 'daily' && nb.folder === 'all' ? 'all' : nb.folder === 'trash' ? folderId : nb.folder; nb.note = n.id; nb.view = 'note'; nb.sort = 'updated'; App.rerender(); const t = document.getElementById('nb-title'); if (t && !n.title) t.focus(); else if (editor) editor.focus(); },
    'nb-title'(el) { clearTimeout(App._nbt); const id = el.dataset.id, v = el.value; App._nbt = setTimeout(() => { S.updateNote(id, { title: v }); const b = document.querySelector(`[data-nb-title="${id}"]`); if (b) b.textContent = v || 'Ohne Titel'; const d = document.querySelector(`[data-nb-date="${id}"]`); if (d) d.textContent = fmt.dateTime(new Date()); }, 400); },
    'nb-select'(el) { const nb = st(); const id = el.dataset.id; nb.selected = nb.selected.includes(id) ? nb.selected.filter(x => x !== id) : [...nb.selected, id]; App.rerender(); },
    'nb-select-all'() { const nb = st(); const all = visibleNotes().map(n => n.id); nb.selected = nb.selected.length === all.length ? [] : all; App.rerender(); },
    'nb-select-mode'() { const nb = st(); nb.selectMode = !nb.selectMode; nb.selected = []; App.rerender(); },
    'nb-move-sel'(el) { const nb = st(); S.moveNotes(nb.selected, el.dataset.id); U.toast(`${nb.selected.length} Notizen verschoben`, 'ok'); nb.selected = []; nb.selectMode = false; App.rerender(); },
    async 'nb-delete-sel'() { const nb = st(); if (await U.confirmModal(`${nb.selected.length} Notizen löschen?`, 'Sie landen für 30 Tage im Papierkorb.', { ok: 'Löschen', danger: true })) { nb.selected.forEach(id => S.trashNote(id)); nb.selected = []; nb.selectMode = false; nb.note = null; App.rerender(); } },
    'nb-move'(el) { flush(); S.moveNotes([el.dataset.id], el.dataset.folder); U.toast('Verschoben', 'ok'); App.rerender(); },
    'nb-duplicate'(el) { flush(); const c = S.duplicateNote(el.dataset.id); if (c) { st().note = c.id; U.toast('Kopie erstellt', 'ok'); App.rerender(); } },
    async 'nb-delete'(el) { flush(); if (await U.confirmModal('Notiz löschen?', 'Sie landet für 30 Tage im Papierkorb und kann dort wiederhergestellt werden.', { ok: 'Löschen', danger: true })) { S.trashNote(el.dataset.id); st().note = null; U.toast('In den Papierkorb verschoben'); App.rerender(); } },
    'nb-trash-restore'(el) { S.restoreNote(el.dataset.id); U.toast('Wiederhergestellt', 'ok'); st().note = null; App.rerender(); },
    async 'nb-trash-purge'(el) { if (await U.confirmModal('Endgültig löschen?', 'Das lässt sich nicht rückgängig machen.', { ok: 'Endgültig löschen', danger: true })) { S.purgeNote(el.dataset.id); st().note = null; App.rerender(); } },
    'nb-trash-restore-sel'() { const nb = st(); nb.selected.forEach(id => S.restoreNote(id)); nb.selected = []; nb.selectMode = false; App.rerender(); },
    async 'nb-trash-purge-sel'() { const nb = st(); if (await U.confirmModal(`${nb.selected.length} Notizen endgültig löschen?`, 'Das lässt sich nicht rückgängig machen.', { ok: 'Endgültig löschen', danger: true })) { nb.selected.forEach(id => S.purgeNote(id)); nb.selected = []; nb.selectMode = false; nb.note = null; App.rerender(); } },
    async 'nb-trash-empty'() { if (await U.confirmModal('Papierkorb leeren?', 'Alle gelöschten Notizen werden endgültig entfernt.', { ok: 'Leeren', danger: true })) { S.emptyTrash(); st().note = null; App.rerender(); } },
    'nb-stats'() { st().statsOpen = !st().statsOpen; App.rerender(); },
    'nb-date-nav'(el) { const nb = st(); const m = nb.pickMonth || new Date(); nb.pickMonth = new Date(m.getFullYear(), m.getMonth() + Number(el.dataset.dir), 1); nb._openPop = 'nbdate'; App.rerender(); },
    'nb-date-pick'(el) { flush(); const n = S.getNote(el.dataset.id); if (!n) return; const old = n.dateKey; const patch = { dateKey: el.dataset.key }; if (n.type === 'day' && (!n.title || (old && n.title === S.dayTitle(old)))) patch.title = S.dayTitle(el.dataset.key); S.updateNote(n.id, patch, false); st().pickMonth = null; App.rerender(); },
    'nb-import'() { const f = document.getElementById('nb-import-file'); if (f) f.click(); },
    'nb-folder-add'() { folderModal(null); },
    'nb-folder-edit'(el) { folderModal(S.getFolder(el.dataset.id), !!el.dataset.color); },
    'fo-color'(el) { const f = el.closest('form'); f.querySelector('input[name=color]').value = el.dataset.value; f.querySelectorAll('.swatch').forEach(b => b.setAttribute('aria-pressed', b === el)); },
    'fo-color-custom'(el) { const f = el.closest('form'); f.querySelector('input[name=color]').value = el.value; f.querySelectorAll('.swatch').forEach(b => b.setAttribute('aria-pressed', 'false')); },
    'nb-folder-save'(form) { const fd = new FormData(form); const name = String(fd.get('name') || '').trim(), color = String(fd.get('color') || '#8b7cf6'); if (!name) return; if (form.dataset.id) S.updateFolder(form.dataset.id, { name, color }); else { const f = S.addFolder(name, color); st().folder = f.id; st().note = null; } U.closeModal(); App.rerender(); },
    'nb-folder-template'(el) { const f = S.getFolder(el.dataset.id); if (!f) return; U.modal(`<form data-action="nb-folder-template-save" data-id="${f.id}"><div class="modal-head"><h2>Standard-Vorlage für „${esc(f.name)}“</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><p class="muted small">Neue Notizen in diesem Ordner starten mit dieser Vorlage.</p><div class="field"><label for="ft-tpl">Vorlage</label><select class="select" id="ft-tpl" name="tpl"><option value="">Keine</option>${S.templates().map(t => `<option value="${t.id}" ${f.defaultTemplateId === t.id ? 'selected' : ''}>${esc(t.name)}</option>`).join('')}</select></div><div class="modal-foot"><button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`, { cls: 'narrow' }); },
    'nb-folder-template-save'(form) { S.updateFolder(form.dataset.id, { defaultTemplateId: new FormData(form).get('tpl') || null }); U.closeModal(); U.toast('Gespeichert', 'ok'); },
    async 'nb-folder-delete'(el) { const f = S.getFolder(el.dataset.id); if (!f) return; const n = S.notes().filter(x => x.folderId === f.id).length; if (await U.confirmModal(`Ordner „${f.name}“ löschen?`, `Achtung: ${n ? `Alle ${n} Notizen darin werden mit gelöscht (30 Tage im Papierkorb).` : 'Der Ordner ist leer.'}`, { ok: 'Ordner löschen', danger: true })) { S.deleteFolder(f.id); const nb = st(); nb.folder = 'all'; nb.note = null; App.rerender(); } },
    'nb-tpl-save'(form) { const m = form.closest('.modal'); const name = String(new FormData(form).get('name') || '').trim(); if (!name || !m._tplEditor) return; const content = m._tplEditor.getContents(); if (form.dataset.id) S.updateTemplate(form.dataset.id, { name, content }); else S.addTemplate(name, content); m._tplEditor.destroy(); U.closeModal(); U.toast('Vorlage gespeichert', 'ok'); App.rerender(); },
    async 'nb-tpl-delete-cur'(el) { if (await U.confirmModal('Vorlage löschen?', '', { ok: 'Löschen', danger: true })) { S.deleteTemplate(el.dataset.id); U.closeModal(); App.rerender(); } },
    async 'nb-tpl-delete'(el) { if (await U.confirmModal('Vorlage löschen?', '', { ok: 'Löschen', danger: true })) { S.deleteTemplate(el.dataset.id); App.rerender(); } },
    'nb-tag-add'(form) { const name = String(new FormData(form).get('tag') || '').trim(); if (!name) return; const t = S.ensureTag(name); const n = S.getNote(form.dataset.id); if (t && n && !(n.tags || []).includes(t.id)) S.updateNote(n.id, { tags: [...(n.tags || []), t.id] }, false); flush(); App.rerender(); },
    'nb-tag-toggle'(el) { const n = S.getNote(el.dataset.id); if (!n) return; const t = el.dataset.tag ? S.noteTags().find(x => x.id === el.dataset.tag) : S.ensureTag(el.dataset.name); if (!t) return; const has = (n.tags || []).includes(t.id); S.updateNote(n.id, { tags: has ? (n.tags || []).filter(x => x !== t.id) : [...(n.tags || []), t.id] }, false); App.rerender(); const pop = document.getElementById('pop-nbtags'); if (pop) pop.classList.add('open'); },
    async 'nb-tag-new'(el) { const name = await U.promptModal('Neuer Tag', { label: 'Name', placeholder: 'z. B. Lehre', ok: 'Anlegen' }); if (!name) return; const t = S.ensureTag(name); const n = S.getNote(el.dataset.id); if (t && n && !(n.tags || []).includes(t.id)) S.updateNote(n.id, { tags: [...(n.tags || []), t.id] }, false); App.rerender(); },
    'nb-tag-remove'(el) { const n = S.getNote(el.dataset.id); if (n) S.updateNote(n.id, { tags: (n.tags || []).filter(x => x !== el.dataset.tag) }, false); const t = S.noteTags().find(x => x.id === el.dataset.tag); if (t && !S.notes().some(x => (x.tags || []).includes(t.id))) S.deleteNoteTag(t.id); flush(); App.rerender(); },
    'nb-share'(el) { flush(); const n = S.getNote(el.dataset.id); if (!n) return; const link = location.href.split('#')[0] + '#share_' + shareToken(n); U.modal(`<div class="modal-head"><h2>Notiz teilen</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><p class="muted small">Wer den Link öffnet, sieht die Notiz nur lesend. Der Inhalt steckt im Link selbst, Bilder werden als Platzhalter angezeigt. Am besten funktioniert das mit der Adresse deiner veröffentlichten Website.</p><textarea class="input mono" id="share-link" readonly style="min-height:90px">${esc(link)}</textarea><div class="modal-foot"><button type="button" class="btn" data-action="nb-copy" data-target="share-link">${I.copy} Link kopieren</button><a class="btn primary" href="${esc(link)}" target="_blank" rel="noopener">${I.external} Öffnen</a></div>`, { cls: 'narrow' }); },
    async 'nb-copy'(el) { const ta = document.getElementById(el.dataset.target); try { await navigator.clipboard.writeText(ta.value); U.toast('Kopiert', 'ok'); } catch (e) { ta.select(); U.toast('Markiert, jetzt mit Strg+C kopieren'); } },
    'nb-export'(el) { flush(); const n = S.getNote(el.dataset.id); if (!n) return; const text = JSON.stringify({ app: 'trading-journal-web', kind: 'note', version: 1, note: { title: n.title, type: n.type, dateKey: n.dateKey || null, tags: (n.tags || []).map(id => (S.noteTags().find(t => t.id === id) || {}).name).filter(Boolean), content: n.content, createdAt: n.createdAt, updatedAt: n.updatedAt } }, null, 2); U.downloadText(`notiz-${(n.title || 'ohne-titel').replace(/[^\wäöüß-]+/gi, '-').toLowerCase()}.json`, text, 'application/json'); },
    'nb-pdf'() { flush(); if (!document.querySelector('#nb-editor')) return; U.toast('Druckdialog: dort „Als PDF speichern“ wählen'); setTimeout(() => window.print(), 150); },
  });
})(typeof self !== 'undefined' ? self : this);
