/* Statistiken: Übersicht, Tage, Setups, Zeit, Fehler, Marktphase, Zustand, Edge, Monte Carlo */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;
  const TABS = [['summary', 'Übersicht'], ['days', 'Tage'], ['setups', 'Setups'], ['time', 'Zeit'], ['mistakes', 'Fehler'], ['regime', 'Marktphase'], ['state', 'Zustand'], ['edge', 'Edge-Check'], ['mc', 'Monte Carlo']];
  const REG_T = { trending: 'Trend', ranging: 'Seitwärts' }, REG_V = { low: 'Vola niedrig', normal: 'Vola normal', high: 'Vola hoch' };
  App.screens.stats = {
    title: 'Statistiken',
    render(ctx) {
      const tab = ctx.params[0] && TABS.some(t => t[0] === ctx.params[0]) ? ctx.params[0] : 'summary'; App.state.statsTab = tab; const list = ctx.inRange; const closed = C.closedOnly(list);
      const days = C.dailyAggregation(list); const r = App.range();
      const chartDays = fillDays(days, r); const id = 'stats-top'; U.chartData[id] = { days: chartDays, bars: false, dots: chartDays.length <= 45 };
      const top = U.card('', `<div class="chart h240" data-chart="pnl" data-id="${id}"></div><div class="legend"><span><i style="background:var(--accent)"></i>Kumulierter Netto-P&L</span></div>`);
      const tabs = `<div class="tabs" style="overflow-x:auto;flex-wrap:nowrap;padding-bottom:2px">${TABS.map(([k, l]) => `<a class="btn" href="#/stats/${k}" aria-pressed="${tab === k}" style="${tab === k ? 'border-color:var(--border-2);background:var(--surface-2)' : 'color:var(--text-2)'}">${l}</a>`).join('')}</div>`;
      const body = ({ summary: tabSummary, days: tabDays, setups: tabSetups, time: tabTime, mistakes: tabMistakes, regime: tabRegime, state: tabState, edge: tabEdge, mc: tabMC })[tab](list, closed, days, ctx);
      return top + tabs + body;
    },
  };
  function fillDays(days, r) { if (!r.from) return days; const map = new Map(days.map(d => [d.key, d])); const out = []; const c = new Date(r.from); const end = new Date(Math.min(r.to.getTime(), Date.now())); while (c <= end) { const k = C.dayKey(c); out.push(map.get(k) || { key: k, day: new Date(c), pnl: 0, n: 0 }); c.setDate(c.getDate() + 1); } return out; }
  function statVal(it) { const v = it.v; switch (it.type) { case 'cur': return `<span class="${U.cls(v)}">${fmt.cur(v, { signed: true })}</span>`; case 'curNeg': return `<span class="${v > 0 ? 'neg' : 'neu'}">${fmt.cur(-v, { signed: true })}</span>`; case 'pct': return fmt.pct(v, 1); case 'factor': return v == null ? '∞' : fmt.num(v, 2); case 'r': return v == null ? '—' : fmt.r(v); case 'dur': return fmt.dur(v); case 'int': return fmt.int(v); default: return fmt.num(v, 1); } }
  function tabSummary(list, closed) {
    if (!closed.length) return U.empty('stats', 'Keine abgeschlossenen Trades im Zeitraum', 'Ändere den Zeitraum oder logge Trades.');
    const st = C.stats16(list); const sk = C.streaks(list);
    return `<section class="card flush"><div class="stat-grid">${st.items.map(it => `<div class="stat"><div class="k">${esc(it.label)}${U.info(it.info)}</div><div class="v">${statVal(it)}</div></div>`).join('')}</div></section>
      <div class="grid three">${U.card('Serien', `${U.kv('Aktuelle Serie', sk.current ? `<span class="${sk.kind === 'win' ? 'pos' : 'neg'}">${sk.current} ${sk.kind === 'win' ? 'Gewinne' : 'Verluste'}</span>` : '—')}${U.kv('Längste Gewinnserie', sk.maxWin)}${U.kv('Längste Verlustserie', sk.maxLoss)}${U.kv('Größter Gewinn', `<span class="pos">${fmt.cur(st.s.largestWin)}</span>`)}${U.kv('Größter Verlust', `<span class="neg">${fmt.cur(st.s.largestLoss)}</span>`)}`)}${U.card('Drawdown & Risiko', `${U.kv('Max. Drawdown', `<span class="neg">${fmt.cur(-st.s.maxDD)}</span>`)}${U.kv('Max. Drawdown vom Konto', fmt.pct(st.s.maxDD / App.account(), 1))}${U.kv('Erholungsfaktor', st.s.maxDD > 0 ? fmt.num(st.s.total / st.s.maxDD, 2) : '∞')}${U.kv('Ø Risiko pro Trade', fmt.cur(C.mean(closed.filter(t => t.risk > 0).map(t => t.risk))))}${U.kv('Gebühren gesamt', fmt.cur(st.s.fees))}`)}${U.card('Haltedauer', `${U.kv('Ø Gewinner', fmt.dur(st.s.winHold))}${U.kv('Ø Verlierer', fmt.dur(st.s.lossHold))}${U.kv('Ø gesamt', fmt.dur(st.s.avgHold))}${U.kv('Trades pro Tag', fmt.num(st.d.avgTrades, 1))}${U.kv('Bester Tag', `<span class="pos">${fmt.cur(st.d.bestDay, { signed: true })}</span>`)}${U.kv('Schlechtester Tag', `<span class="neg">${fmt.cur(st.d.worstDay, { signed: true })}</span>`)}`)}</div>`;
  }
  function tabDays(list, closed, days) {
    if (!days.length) return U.empty('day', 'Keine Handelstage im Zeitraum', '');
    const ds = C.daySummary(days); const idw = 'stats-wd'; U.chartData[idw] = { groups: C.timeAnalysis(list).weekdays, metric: 'total' };
    return `<div class="grid two">${U.card('P&L nach Wochentag', `<div class="chart h240" data-chart="vbars" data-id="${idw}"></div>`)}${U.card('Tage im Überblick', `${U.kv('Handelstage', ds.days)}${U.kv('Gewinntage / Verlusttage', `<span class="pos">${ds.winDays}</span> / <span class="neg">${ds.lossDays}</span>`)}${U.kv('Ø Gewinntag', `<span class="pos">${fmt.cur(ds.avgWinDay)}</span>`)}${U.kv('Ø Verlusttag', `<span class="neg">${fmt.cur(ds.avgLossDay)}</span>`)}${U.kv('Tages-Profit-Faktor', fmt.factor(ds.dayPF))}${U.kv('Ø Trades pro Tag', fmt.num(ds.avgTrades, 1))}`)}</div>
      <div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Tag</th><th class="r">Trades</th><th class="r">Gewinner</th><th class="r">Verlierer</th><th class="r">Win-Rate</th><th class="r">Brutto</th><th class="r">Gebühren</th><th class="r">Netto-P&L</th><th class="r">Drawdown</th></tr></thead><tbody>${days.slice().reverse().map(d => `<tr class="link" data-action="day" data-day="${d.key}"><td>${fmt.weekdayLong(d.day)}</td><td class="r">${d.n}</td><td class="r pos">${d.wins}</td><td class="r neg">${d.losses}</td><td class="r">${fmt.pct(d.winRate)}</td><td class="r">${fmt.cur(d.gross, { signed: true })}</td><td class="r">${fmt.cur(d.fees)}</td><td class="r">${U.pnl(d.pnl)}</td><td class="r neg">${d.intradayDD ? fmt.cur(-d.intradayDD) : '—'}</td></tr>`).join('')}</tbody></table></div>`;
  }
  function groupTable(groups, keyLabel) { return `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>${keyLabel}</th><th class="r">Trades</th><th class="r">Win-Rate</th><th class="r">Ø pro Trade</th><th class="r">Ø R</th><th class="r">Profit-Faktor</th><th class="r">Netto-P&L</th></tr></thead><tbody>${groups.map(g => `<tr><td><b>${esc(g.label || g.key)}</b></td><td class="r">${g.s.n}</td><td class="r">${fmt.pct(g.s.winRate)}</td><td class="r">${U.pnl(g.s.expectancy)}</td><td class="r">${U.rText(g.s.avgR)}</td><td class="r">${fmt.factor(g.s.pf)}</td><td class="r">${U.pnl(g.s.total)}</td></tr>`).join('')}</tbody></table></div>`; }
  function tabSetups(list, closed) {
    const setups = C.groupBy(list, t => t.setup || 'Ohne Setup'); const strategies = C.groupBy(list, t => t.strategy || 'Ohne Strategie'); const symbols = C.groupBy(list, t => t.symbol); const dirs = C.groupBy(list, t => t.direction > 0 ? 'Long' : 'Short');
    if (!closed.length) return U.empty('strategy', 'Keine Trades im Zeitraum', '');
    U.chartData['st-setups'] = { groups: setups, metric: 'expectancy' }; U.chartData['st-sym'] = { groups: symbols, metric: 'total' };
    return `<div class="grid two">${U.card('Erwartungswert je Setup', `<div class="chart h240" data-chart="hbars" data-id="st-setups"></div>`, { info: 'Ø Netto-P&L pro Trade je Setup.' })}${U.card('Netto-P&L je Symbol', `<div class="chart h240" data-chart="vbars" data-id="st-sym"></div>`)}</div>${U.card('Setups', groupTable(setups, 'Setup'))}<div class="grid two">${U.card('Strategien', groupTable(strategies, 'Strategie'))}${U.card('Richtung', groupTable(dirs, 'Richtung'))}</div>`;
  }
  function tabTime(list, closed) {
    if (!closed.length) return U.empty('clock', 'Keine Trades im Zeitraum', '');
    const ta = C.timeAnalysis(list); U.chartData['t-wd'] = { groups: ta.weekdays, metric: 'expectancy' }; U.chartData['t-h'] = { groups: ta.hours, metric: 'total' }; U.chartData['t-hold'] = { groups: ta.holding, metric: 'expectancy' };
    const s = C.summary(list);
    return `<div class="grid two">${U.card('Ø pro Trade nach Wochentag', `<div class="chart h240" data-chart="vbars" data-id="t-wd"></div>`)}${U.card('Netto-P&L nach Uhrzeit', `<div class="chart h240" data-chart="vbars" data-id="t-h"></div>`)}</div><div class="grid two">${U.card('Ø pro Trade nach Haltedauer', `<div class="chart h240" data-chart="hbars" data-id="t-hold"></div>`)}${U.card('Haltedauer Gewinner vs. Verlierer', `<div class="row" style="gap:24px;margin-bottom:10px"><div><div class="caption">Gewinner</div><div class="score-big pos">${fmt.dur(s.winHold)}</div></div><div><div class="caption">Verlierer</div><div class="score-big neg">${fmt.dur(s.lossHold)}</div></div></div><p class="small muted">${s.lossHold > s.winHold * 1.3 ? 'Du hältst Verlierer deutlich länger als Gewinner. Prüfe, ob du bei Verlusten hoffst und bei Gewinnen zu früh aussteigst.' : s.winHold > s.lossHold * 1.3 ? 'Gewinner laufen länger als Verlierer. Das ist das gesunde Muster: Verluste klein halten, Gewinne laufen lassen.' : 'Gewinner und Verlierer laufen ähnlich lang.'}</p>`)}</div>${U.card('Uhrzeiten im Detail', groupTable(ta.hours, 'Uhrzeit'))}`;
  }
  function tabMistakes(list, closed) {
    if (!closed.length) return U.empty('warning', 'Keine Trades im Zeitraum', '');
    const mr = C.mistakeReport(list); const emo = C.groupBy(list, t => t.emotions.length ? t.emotions : ['Ohne Angabe']); U.chartData['m-emo'] = { groups: emo, metric: 'expectancy' };
    const max = Math.max(1, ...mr.items.map(x => Math.abs(x.total)));
    return `<div class="grid tiles">${U.tile('Fehler haben gekostet', `<span class="${mr.cost < -C.EPS ? 'neg' : 'neu'}">${fmt.cur(mr.cost, { signed: true })}</span>`, { info: 'Tatsächliches Ergebnis minus Ergebnis ohne Trades mit Fehler-Tags oder gebrochenen Regeln.' })}${U.tile('Ergebnis ohne Fehler', U.pnl(mr.compliant, '', { signed: true }), { n: `${mr.compliantN} Trades` })}${U.tile('Trades mit Fehlern', `${mr.mistakeN}`, { foot: `${fmt.pct(mr.n ? mr.mistakeN / mr.n : 0)} aller Trades` })}${U.tile('Win-Rate mit / ohne Fehler', `<span class="neg">${fmt.pct(mr.mistakeSummary.winRate)}</span> <span class="muted">/</span> <span class="pos">${fmt.pct(mr.compliantSummary.winRate)}</span>`)}</div>
      <div class="grid two">${U.card('Kosten je Fehler', mr.items.length ? mr.items.map(it => U.barRow(it.name, it.total, max, `${fmt.cur(it.total, { signed: true })} · ${it.n}× · WR ${fmt.pct(it.n ? it.wins / it.n : 0)}`, it.total < 0 ? 'var(--loss)' : 'var(--profit)')).join('') : '<div class="muted small">Keine Fehler-Tags vergeben. Sehr gut, oder ehrlich bleiben?</div>', { info: 'Summe des Netto-P&L aller Trades mit diesem Tag.' })}${U.card('Erwartungswert nach Emotion', `<div class="chart h280" data-chart="hbars" data-id="m-emo"></div>`)}</div>`;
  }
  function tabRegime(list, closed) {
    const ra = C.regimeAnalysis(list, S.regimeByDay()); if (!ra.coverage) return U.empty('trend', 'Keine Marktphasen erfasst', 'Lege in der Tagesansicht oder beim Beenden der Session fest, ob der Tag ein Trend- oder Seitwärtstag war.');
    const lab = g => Object.assign(g, { label: g.key.includes('|') ? `${REG_T[g.key.split('|')[0]]} · ${REG_V[g.key.split('|')[1]]}` : REG_T[g.key] || REG_V[g.key] || g.key });
    U.chartData['r-t'] = { groups: ra.trend.map(lab), metric: 'expectancy' }; U.chartData['r-v'] = { groups: ra.vol.map(lab), metric: 'expectancy' };
    return `<div class="muted small">${ra.coverage} von ${closed.length} Trades haben eine Marktphase.</div><div class="grid two">${U.card('Ø pro Trade: Trend vs. Seitwärts', `<div class="chart h220" data-chart="vbars" data-id="r-t"></div>`)}${U.card('Ø pro Trade nach Volatilität', `<div class="chart h220" data-chart="vbars" data-id="r-v"></div>`)}</div>${U.card('Kombinationen', groupTable(ra.combined.map(lab), 'Marktphase'))}${U.card('Setups je Marktphase', (() => { const rb = S.regimeByDay(); const rows = []; for (const trend of ['trending', 'ranging']) { const sub = closed.filter(t => (rb[t.dayKey] || {}).trend === trend); const g = C.groupBy(sub, t => t.setup || 'Ohne Setup'); for (const x of g) rows.push({ label: `${REG_T[trend]} · ${x.key}`, s: x.s }); } return rows.length ? groupTable(rows, 'Phase · Setup') : '<div class="muted small">Noch keine Kombinationen.</div>'; })())}`;
  }
  function tabState(list, closed, days) {
    const st = C.stateAnalysis(days, S.checkInByDay()); if (!st.n) return U.empty('sparkle', 'Keine Check-ins im Zeitraum', 'Starte den Tag mit „Session starten“, dann siehst du hier, wie Schlaf, Stress und Stimmung mit deinem Ergebnis zusammenhängen.');
    const block = (title, m) => U.card(title, `<div class="row between" style="margin-bottom:8px"><span class="muted small">${m.n} Tage</span><span class="small">Korrelation <b class="${m.r == null ? '' : m.r > 0.2 ? 'pos' : m.r < -0.2 ? 'neg' : ''}">${m.r == null ? '—' : fmt.num(m.r, 2)}</b></span></div>${m.groups.map(g => U.barRow(`${g.label} (${g.n})`, g.avg, Math.max(1, ...m.groups.map(x => Math.abs(x.avg))), `${fmt.cur(g.avg, { signed: true })} · ${fmt.pct(g.winRate)} Tage im Plus`, g.avg >= 0 ? 'var(--profit)' : 'var(--loss)')).join('')}`);
    return `<div class="muted small">${st.n} Handelstage mit Check-in. Korrelation von −1 bis +1 zwischen Wert und Tages-P&L.</div><div class="grid three">${block('Schlaf', st.sleep)}${block('Stress', st.stress)}${block('Stimmung', st.mood)}</div>`;
  }
  function tabEdge(list, closed) {
    const e = C.edge(list); U.chartData['edge'] = { edge: e };
    const V = { insufficient: ['neutral', 'Zu wenig Daten', `Mindestens ${e.minSample} Trades mit R-Wert nötig, aktuell ${e.n}.`], positive: ['win', 'Edge belegt', 'Das 95-%-Intervall liegt komplett über Null.'], negative: ['loss', 'Negativer Edge', 'Das 95-%-Intervall liegt komplett unter Null.'], unproven: ['warn', 'Nicht belegt', 'Das Intervall schließt Null ein. Mehr Trades oder bessere Ausführung nötig.'] }[e.verdict];
    return `<div class="grid tiles">${U.tile('Ø R pro Trade', U.rText(e.mean), { n: `${e.n} Trades`, info: 'Mittelwert des realisierten R-Multiples.' })}${U.tile('95-%-Intervall', `<span class="small" style="font-size:20px">${fmt.r(e.low)} bis ${fmt.r(e.high)}</span>`, { info: 'Konfidenzintervall des Mittelwerts (t-Verteilung).' })}${U.tile('Urteil', U.pill(V[1], V[0]), { foot: V[2] })}${U.tile('Nötige Stichprobe', e.required ? `${e.required}` : '—', { info: 'Anzahl Trades, ab der der Mittelwert bei gleicher Streuung signifikant von Null verschieden wäre.', foot: e.required && e.required > e.n ? `noch ${e.required - e.n} Trades` : 'erreicht' })}</div>
      ${U.card('Rollierender Edge', `<div class="chart h280" data-chart="rolling" data-id="edge"></div>${e.deteriorating ? `<div class="banner warn" style="margin-top:12px">${I.warning}<div><b>Dein Edge lässt nach</b>Die letzten ${e.window} Trades liegen bei ${fmt.r(e.recent)}, der Gesamtschnitt bei ${fmt.r(e.mean)}.</div></div>` : ''}`, { info: `Gleitender Durchschnitt des R-Multiples über die letzten ${e.window} Trades.`, sub: `Standardabweichung ${fmt.num(e.sd, 2)} R · Standardfehler ${fmt.num(e.se, 3)} R` })}`;
  }
  function tabMC(list, closed) {
    const account = App.account(); const mc = C.monteCarlo(list, { account, ruinPct: (S.settings.ruinDrawdownPct || 30) / 100, runs: S.settings.mcRuns || 1000, seed: App.state.mcSeed || 7 });
    if (!mc) return U.empty('dice', 'Mindestens 10 abgeschlossene Trades nötig', 'Die Simulation zieht zufällig aus deinen bisherigen Trades.');
    U.chartData['mc'] = { mc }; U.chartData['mc-h'] = { mc };
    return `<div class="row between"><div class="muted small">${mc.runs} Durchläufe à ${mc.horizon} Trades, gezogen mit Zurücklegen aus ${closed.length} Trades. Startkapital ${fmt.cur(mc.start)}, Ruin bei ${fmt.pct(mc.ruinPct)} Drawdown.</div><button type="button" class="btn sm" data-action="mc-reroll">${I.dice} Neu simulieren</button></div>
      <div class="grid tiles">${U.tile('Ruin-Wahrscheinlichkeit', `<span class="${mc.ruin > 0.1 ? 'neg' : mc.ruin > 0.02 ? 'warn' : 'pos'}">${fmt.pct(mc.ruin, 1)}</span>`, { info: 'Anteil der Durchläufe, die die Ruin-Schwelle berühren.' })}${U.tile('Gewinnwahrscheinlichkeit', `<span class="${mc.prob > 0.5 ? 'pos' : 'neg'}">${fmt.pct(mc.prob, 1)}</span>`, { info: 'Anteil der Durchläufe, die über dem Startkapital enden.' })}${U.tile('Median-Drawdown', `<span class="neg">${fmt.cur(-mc.dd.p50)}</span>`, { foot: `95 %: ${fmt.cur(-mc.dd.p95)} · schlimmster ${fmt.cur(-mc.dd.worst)}` })}${U.tile('Endkapital (Median)', fmt.cur(mc.final.p50), { foot: `5 %: ${fmt.cur(mc.final.p5)} · 95 %: ${fmt.cur(mc.final.p95)}` })}</div>
      <div class="grid main-side">${U.card('Beispielpfade', `<div class="chart h300" data-chart="mc" data-id="mc"></div>`, { sub: '25 von ' + mc.runs + ' Durchläufen' })}${U.card('Verteilung der Drawdowns', `<div class="chart h300" data-chart="hist" data-id="mc-h"></div>`, { info: 'Maximaler Drawdown je Durchlauf in Prozent des Startkapitals.' })}</div>`;
  }
  Object.assign(App.actions, { 'mc-reroll'() { App.state.mcSeed = Math.floor(Math.random() * 1e6); App.rerender(); } });
})(typeof self !== 'undefined' ? self : this);
