/* TradeLog: Liste, Tageskarten, Verpasste Trades, Trade-Detail */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt, App = root.App;

  const COLS = [
    ['openedAt', 'Datum'], ['pnl', 'Netto-P&L', 'r'], ['symbol', 'Symbol'], ['status', 'Status'], ['open', 'Eröffnung'], ['close', 'Schluss'], ['entryPrice', 'Einstieg', 'r'], ['exitPrice', 'Ausstieg', 'r'], ['r', 'Netto-R', 'r'], ['setup', 'Setup'], ['strategy', 'Strategie'], ['rules', 'Regeln', 'r'], ['score', 'Score', 'r'],
  ];
  function filtered(list) {
    const f = App.state.tradeFilter; const q = f.q.trim().toLowerCase();
    return list.filter(t => (!f.symbol || t.symbol === f.symbol) && (!f.setup || t.setup === f.setup) && (!f.status || t.status === f.status) && (!f.mistake || t.mistakes.includes(f.mistake) || (f.mistake === '__any' && t.mistakes.length)) && (!q || [t.symbol, t.setup, t.strategy, t.notes, ...(t.mistakes || []), ...(t.emotions || [])].join(' ').toLowerCase().includes(q)));
  }
  function sorted(list) {
    const { key, dir } = App.state.tradeSort; const val = t => key === 'openedAt' || key === 'open' ? t.open.getTime() : key === 'close' ? (t.close ? t.close.getTime() : 0) : key === 'rules' ? (t.rulesBroken.length ? 0 : 1) : key === 'score' ? C.discipline(t).score : key === 'status' ? ({ win: 3, be: 2, loss: 1, open: 0 })[t.status] : t[key] == null ? -Infinity : t[key];
    return list.slice().sort((a, b) => { const x = val(a), y = val(b); if (x === y) return b.sortTime - a.sortTime; return (x > y ? 1 : -1) * dir; });
  }
  App.screens.trades = {
    title(ctx) { return ctx.params[0] ? 'Trade' : 'TradeLog'; },
    actions(ctx) { return ctx.params[0] ? '' : `<button type="button" class="btn hide-m" data-action="import">${I.upload}<span>CSV importieren</span></button>`; },
    render(ctx) {
      if (ctx.params[0]) return renderDetail(ctx.params[0], ctx);
      const view = App.state.tradeFilter.view; const list = ctx.inRange; const s = C.summary(list);
      const head = `<div class="grid tiles">
        ${U.tile('Netto-P&L kumuliert', U.pnl(s.total, '', { signed: false }), { n: `${s.n}`, info: 'Summe aller abgeschlossenen Trades im Zeitraum.' })}
        ${U.tile('Profit-Faktor', s.n ? fmt.factor(s.pf) : '—', { info: 'Bruttogewinn geteilt durch Bruttoverlust.' })}
        ${U.tile('Trade-Win-Rate', fmt.pct(s.winRate, 1), { info: 'Anteil der Gewinn-Trades.', gauge: `<span class="pills">${U.pill(s.wins, 'win')}${U.pill(s.be, 'be')}${U.pill(s.losses, 'loss')}</span>` })}
        ${U.tile('Ø Gewinn / Verlust', s.payoff == null ? (s.avgWin > 0 ? '∞' : '—') : fmt.num(s.payoff, 2), { info: 'Durchschnittlicher Gewinn geteilt durch durchschnittlichen Verlust.' })}
      </div>`;
      const tabs = U.tabs([['trades', 'Trades'], ['days', 'Tage'], ['missed', 'Verpasste Trades']], view, 'trades-view');
      return head + `<div class="row between">${tabs}${view === 'missed' ? `<button type="button" class="btn sm" data-action="new-missed">${I.plus} Verpassten Trade notieren</button>` : ''}</div>` + (view === 'days' ? renderDays(list) : view === 'missed' ? renderMissed() : renderTable(list, ctx));
    },
  };
  function renderTable(list, ctx) {
    const f = App.state.tradeFilter; const symbols = [...new Set(ctx.all.map(t => t.symbol))].sort(); const setups = [...new Set(ctx.all.map(t => t.setup).filter(Boolean))].sort(); const mistakes = [...new Set(ctx.all.flatMap(t => t.mistakes))].sort();
    const rows = sorted(filtered(list)); const { key, dir } = App.state.tradeSort;
    const filters = `<div class="row" style="gap:8px"><div class="grow" style="max-width:260px;position:relative"><input class="input" id="tf-q" data-input="trade-q" value="${esc(f.q)}" placeholder="Suchen: Symbol, Setup, Notiz …" aria-label="Suchen" style="padding-left:34px"><span style="position:absolute;left:11px;top:11px;width:15px;height:15px;color:var(--muted)">${I.search}</span></div>
      <select class="select" style="width:auto" data-change="trade-filter" data-key="symbol" aria-label="Symbol"><option value="">Alle Symbole</option>${symbols.map(x => `<option ${f.symbol === x ? 'selected' : ''}>${esc(x)}</option>`).join('')}</select>
      <select class="select" style="width:auto" data-change="trade-filter" data-key="setup" aria-label="Setup"><option value="">Alle Setups</option>${setups.map(x => `<option ${f.setup === x ? 'selected' : ''}>${esc(x)}</option>`).join('')}</select>
      <select class="select" style="width:auto" data-change="trade-filter" data-key="status" aria-label="Status"><option value="">Alle Ergebnisse</option><option value="win" ${f.status === 'win' ? 'selected' : ''}>Gewinn</option><option value="loss" ${f.status === 'loss' ? 'selected' : ''}>Verlust</option><option value="be" ${f.status === 'be' ? 'selected' : ''}>Break-even</option><option value="open" ${f.status === 'open' ? 'selected' : ''}>Offen</option></select>
      <select class="select" style="width:auto" data-change="trade-filter" data-key="mistake" aria-label="Fehler"><option value="">Fehler: alle</option><option value="__any" ${f.mistake === '__any' ? 'selected' : ''}>Nur mit Fehler</option>${mistakes.map(x => `<option value="${esc(x)}" ${f.mistake === x ? 'selected' : ''}>${esc(x)}</option>`).join('')}</select>
      ${(f.q || f.symbol || f.setup || f.status || f.mistake) ? `<button type="button" class="btn sm ghost" data-action="trade-filter-reset">${I.close} Zurücksetzen</button>` : ''}<span class="muted small" style="margin-left:auto">${rows.length} von ${list.length} Trades</span></div>`;
    if (!rows.length) return filters + U.empty('tradelog', list.length ? 'Keine Trades passen zum Filter' : 'Keine Trades im Zeitraum', list.length ? 'Ändere die Filter oder den Zeitraum.' : 'Logge einen Trade oder importiere eine CSV-Datei.', list.length ? '' : `<div class="row"><button type="button" class="btn sm" data-action="import">${I.upload} CSV importieren</button><button type="button" class="btn sm primary" data-action="new-trade">${I.plus} Trade loggen</button></div>`);
    const th = COLS.map(([k, l, al]) => `<th class="sortable ${al || ''}" data-action="trade-sort" data-key="${k}">${l}${key === k ? `<span class="dir">${dir > 0 ? '▲' : '▼'}</span>` : ''}</th>`).join('');
    const tr = rows.map(t => { const sc = C.discipline(t).score; return `<tr class="link" data-action="trade" data-id="${t.id}"><td>${fmt.dateFull(t.open)}</td><td class="r">${t.closed ? U.pnl(t.pnl) : '<span class="faint">—</span>'}</td><td class="sym">${esc(t.symbol)} ${U.badge(t.direction)}</td><td>${U.statusPill(t.status)}</td><td>${fmt.time(t.open)}</td><td>${t.close ? fmt.dateFull(t.close) + ' ' + fmt.time(t.close) : '<span class="faint">offen</span>'}</td><td class="r">${fmt.price(t.entryPrice)}</td><td class="r">${t.exitPrice != null ? fmt.price(t.exitPrice) : '—'}</td><td class="r">${U.rText(t.r)}</td><td>${t.setup ? U.chip(t.setup, 'setup') : '<span class="faint">—</span>'}</td><td>${esc(t.strategy || '—')}</td><td class="r">${t.rulesBroken.length ? `<span class="neg" data-tip="${esc(t.rulesBroken.join(', '))}">${I.close.replace('<svg', '<svg style="width:14px;height:14px;display:inline"')}</span>` : `<span class="pos">${I.check.replace('<svg', '<svg style="width:14px;height:14px;display:inline"')}</span>`}</td><td class="r"><b style="color:${U.scoreColor(sc)}">${sc}</b></td></tr>`; }).join('');
    return filters + `<div class="tbl-wrap"><table class="tbl"><thead><tr>${th}</tr></thead><tbody>${tr}</tbody></table></div>`;
  }
  function renderDays(list) {
    const days = C.dailyAggregation(list).slice().reverse(); if (!days.length) return U.empty('day', 'Keine Handelstage im Zeitraum', 'Sobald Trades abgeschlossen sind, erscheinen hier Tageskarten.');
    return `<div class="stack" style="gap:14px">${days.map(d => { const id = 'spark-' + d.key; let c = 0; U.chartData[id] = { values: d.trades.map(t => (c += t.pnl)) }; const gross = d.gross; return `<section class="card day-card"><div class="head"><span class="date">${fmt.weekdayLong(d.day)}</span><span class="pnl ${U.cls(d.pnl)}">Netto ${fmt.cur(d.pnl, { signed: true })}</span><a class="btn sm ghost" style="margin-left:auto" href="#/day/${d.key}">Tagesansicht ${I.chevR}</a></div><div class="body" style="margin-top:12px"><div class="chart h80" data-chart="spark" data-id="${id}"></div><div class="stats" style="margin-top:0"><div><div class="k">Trades</div><div class="v">${d.n}</div></div><div><div class="k">Brutto-P&L</div><div class="v ${U.cls(gross)}">${fmt.cur(gross, { signed: true })}</div></div><div><div class="k">Gewinner / Verlierer</div><div class="v"><span class="pos">${d.wins}</span> / <span class="neg">${d.losses}</span></div></div><div><div class="k">Gebühren</div><div class="v">${fmt.cur(d.fees)}</div></div><div><div class="k">Win-Rate</div><div class="v">${fmt.pct(d.winRate)}</div></div><div><div class="k">Volumen</div><div class="v">${fmt.num(d.volume, 2)}</div></div><div><div class="k">Profit-Faktor</div><div class="v">${fmt.factor(d.pf)}</div></div></div></div></section>`; }).join('')}</div>`;
  }
  function renderMissed() {
    const m = S.data.missed.slice().sort((a, b) => (b.date || '').localeCompare(a.date || '')); if (!m.length) return U.empty('eye', 'Keine verpassten Trades notiert', 'Setups, die du gesehen, aber nicht gehandelt hast. So erkennst du, ob Zögern dich Geld kostet.');
    const total = C.sum(m.map(x => Number(x.pnl) || 0)); const wins = m.filter(x => x.pnl > 0).length;
    return U.card('Verpasste Trades', `<div class="row" style="gap:18px;margin-bottom:12px"><div><div class="caption">Entgangen</div><div class="score-big ${U.cls(total)}">${fmt.cur(total, { signed: true })}</div></div><div><div class="caption">Wären Gewinner gewesen</div><div class="score-big">${wins} von ${m.length}</div></div></div><div class="tbl-wrap inset"><table class="tbl compact"><thead><tr><th>Datum</th><th>Symbol</th><th>Setup</th><th>Grund</th><th class="r">Hätte gebracht</th><th class="r">R</th><th></th></tr></thead><tbody>${m.map(x => `<tr><td>${fmt.dateFull(C.parseDayKey(x.date))}</td><td class="sym">${esc(x.symbol)} ${U.badge(x.direction)}</td><td>${x.setup ? U.chip(x.setup, 'setup') : '—'}</td><td style="white-space:normal;min-width:200px">${esc(x.reason || '')}</td><td class="r">${U.pnl(x.pnl)}</td><td class="r">${U.rText(x.r)}</td><td class="r"><button type="button" class="btn ghost icon sm" data-action="delete-missed" data-id="${x.id}" aria-label="Löschen">${I.trash}</button></td></tr>`).join('')}</tbody></table></div>`, { info: 'Trades, die du nicht genommen hast. Mit dem hypothetischen Ergebnis siehst du, was Zögern kostet.' });
  }
  /* ---------- Detail ---------- */
  function renderDetail(id, ctx) {
    const raw = S.getTrade(id); if (!raw) return U.empty('tradelog', 'Trade nicht gefunden', 'Vielleicht wurde er gelöscht.', `<a class="btn sm" href="#/trades">Zurück zum TradeLog</a>`);
    const t = C.derive(raw); const disc = C.discipline(t); const day = S.day(t.dayKey); const reg = day && day.regime;
    const head = `<div class="row"><a class="btn ghost sm" href="#/trades">${I.back} TradeLog</a><span class="muted small">·</span><a class="btn ghost sm" href="#/day/${t.dayKey}">${I.day} ${fmt.dateFull(t.open)}</a></div>
      <section class="card"><div class="detail-head"><span class="sym">${esc(t.symbol)}</span>${U.badge(t.direction)}${U.statusPill(t.status)}${t.setup ? U.chip(t.setup, 'setup') : ''}${t.strategy ? U.chip(t.strategy) : ''}${reg ? U.chip(`${reg.trend === 'trending' ? 'Trend' : reg.trend === 'ranging' ? 'Seitwärts' : ''}${reg.vol ? ' · Vola ' + ({ low: 'niedrig', normal: 'normal', high: 'hoch' })[reg.vol] : ''}`) : ''}<div class="big">${t.closed ? U.pnl(t.pnl) : '<span class="muted">offen</span>'}${t.r != null ? ` <span class="small muted" style="font-weight:500">${fmt.r(t.r)}</span>` : ''}</div></div>
      </section><section class="card flush"><div class="stat-grid">${[['Eröffnung', fmt.dateTime(t.open)], ['Schluss', t.close ? fmt.dateTime(t.close) : '—'], ['Einstieg', fmt.price(t.entryPrice)], ['Ausstieg', t.exitPrice != null ? fmt.price(t.exitPrice) : '—'], ['Stück × Punktwert', `${fmt.num(t.quantity, 4)} × ${fmt.num(t.multiplier, 2)}`], ['Gebühren', fmt.cur(t.fees)], ['Risiko', t.risk ? fmt.cur(t.risk) : '—'], ['Haltedauer', fmt.dur(t.holdingMin)], ['Bewertung', t.rating ? '★'.repeat(t.rating) + '<span class="faint">' + '★'.repeat(5 - t.rating) + '</span>' : '—']].map(([k, v]) => `<div class="stat" style="padding:12px 20px"><div class="k">${k}</div><div class="v" style="font-size:16px">${v}</div></div>`).join('')}</div></section>`;
    const planCard = U.card('Plan vs. Ausführung', t.plannedStop != null || t.plannedEntry != null ? `<div class="tbl-wrap inset"><table class="tbl compact wrap"><thead><tr><th></th><th class="r">Geplant</th><th class="r">Tatsächlich</th><th class="r">Abweichung</th></tr></thead><tbody>
      <tr><td>Einstieg</td><td class="r">${t.plannedEntry != null ? fmt.price(t.plannedEntry) : '—'}</td><td class="r">${fmt.price(t.entryPrice)}</td><td class="r">${t.plannedEntry != null && t.stopDist ? `<span class="${Math.abs(t.entryPrice - t.plannedEntry) / t.stopDist > 0.25 ? 'warn' : 'pos'}">${fmt.num(Math.abs(t.entryPrice - t.plannedEntry) / t.stopDist, 2)} R</span>` : '—'}</td></tr>
      <tr><td>Stop</td><td class="r">${t.plannedStop != null ? fmt.price(t.plannedStop) : '—'}</td><td class="r">${t.closed && t.status === 'loss' ? fmt.price(t.exitPrice) : '—'}</td><td class="r">${t.closed && t.status === 'loss' && t.r != null ? `<span class="${t.r < -1.15 ? 'neg' : 'pos'}">${t.r < -1.15 ? `${fmt.r(t.r)} statt −1 R` : 'eingehalten'}</span>` : '—'}</td></tr>
      <tr><td>Ziel</td><td class="r">${t.plannedTarget != null ? fmt.price(t.plannedTarget) : '—'}</td><td class="r">${t.exitPrice != null ? fmt.price(t.exitPrice) : '—'}</td><td class="r">${t.plannedR != null ? `geplant ${fmt.r(t.plannedR, false)}${t.r != null ? `, erreicht ${fmt.r(t.r)}` : ''}` : '—'}</td></tr></tbody></table></div>
      ${t.plannedReason ? `<div class="divider"></div><div class="small muted">Begründung</div><div>${esc(t.plannedReason)}</div>` : ''}` : U.empty('target', 'Kein Plan hinterlegt', 'Trage geplanten Einstieg, Stop und Ziel ein, um Plan und Ausführung zu vergleichen.', `<button type="button" class="btn sm" data-action="edit-trade" data-id="${t.id}">Plan ergänzen</button>`), { info: 'Vergleich von geplantem Einstieg, Stop und Ziel mit der tatsächlichen Ausführung.' });
    const discCard = U.card('Disziplin', `<div class="row" style="gap:16px;align-items:center">${U.ring(disc.score, 90, 9)}<div class="grow">${disc.comps.map(c => `<div class="comp"><span>${esc(c.label)}</span><span class="pts" style="color:${c.f >= 0.99 ? 'var(--accent)' : c.f > 0 ? 'var(--warn)' : 'var(--loss)'}">${Math.round(c.f * c.w)} / ${c.w}</span></div>`).join('')}</div></div>`, { info: 'Plan 25, Einstieg 20, Stop 25, keine Fehler-Tags 20, Regeln 10 Punkte.' });
    const excCard = U.card('MAE / MFE', t.maeR != null || t.mfeR != null ? `<div class="excursion">${excBar('Maximal gegen dich (MAE)', t.maeR, 'loss')}${excBar('Maximal für dich (MFE)', t.mfeR, 'profit')}${t.r != null ? excBar('Realisiert', t.r, t.r >= 0 ? 'profit' : 'loss') : ''}</div><div class="small muted" style="margin-top:10px">${t.mfeR != null && t.r != null && t.mfeR - t.r > 0.5 ? `Du hast ${fmt.num(t.mfeR - t.r, 2)} R vom Höchststand liegen lassen.` : t.maeR != null && t.maeR > 0.9 && t.status === 'win' ? 'Der Trade lief fast bis zum Stop, bevor er drehte. Glück oder Geduld?' : 'Skala in R, bezogen auf den geplanten Stop-Abstand.'}</div>` : U.empty('trend', 'Keine Exkursionsdaten', 'Trage MAE und MFE im Editor ein.'), { info: 'Maximale Bewegung gegen dich (MAE) und für dich (MFE) während des Trades, gemessen in R.' });
    const tagsCard = U.card('Tags & Notizen', `<div class="stack"><div><div class="caption" style="margin-bottom:6px">Fehler</div>${t.mistakes.length ? `<div class="chips">${t.mistakes.map(m => U.chip(m, 'mistake')).join('')}</div>` : '<span class="pos small">Keine Fehler markiert</span>'}</div><div><div class="caption" style="margin-bottom:6px">Emotionen</div>${t.emotions.length ? `<div class="chips">${t.emotions.map(m => U.chip(m, 'emotion')).join('')}</div>` : '<span class="faint small">—</span>'}</div>${t.rulesBroken.length ? `<div><div class="caption" style="margin-bottom:6px">Gebrochene Regeln</div><div class="chips">${t.rulesBroken.map(m => U.chip(m, 'rule')).join('')}</div></div>` : ''}<div><div class="caption" style="margin-bottom:6px">Notizen</div><div style="white-space:pre-wrap">${t.notes ? esc(t.notes) : '<span class="faint">Keine Notizen</span>'}</div></div></div>`);
    const shots = t.screenshots.length ? `<div class="shots">${t.screenshots.map(id => `<div class="shot"><img data-blob="${id}" alt="Screenshot" data-action="lightbox" data-blob-id="${id}"><button type="button" class="btn icon sm del" data-action="delete-shot" data-trade="${t.id}" data-blob="${id}" aria-label="Screenshot löschen">${I.trash}</button></div>`).join('')}</div>` : '';
    const shotCard = U.card('Screenshots', `${shots}<div class="dropzone" id="shot-drop" style="margin-top:${shots ? '12px' : '0'}">${I.image}<div>Bilder hierher ziehen, einfügen (Strg+V) oder klicken</div><input type="file" id="shot-file" accept="image/*" multiple class="hidden"></div>`, { info: 'Chart-Screenshots zum Trade. Werden lokal im Browser gespeichert.' });
    const voice = t.voiceNotes.length ? t.voiceNotes.map(v => { const sent = v.sentiment || C.sentiment(v.transcript); return `<div class="voice"><div class="grow"><div class="row"><b>${fmt.dateTime(v.createdAt)}</b>${v.transcript ? U.pill(sent.label, sent.label === 'positiv' ? 'win' : sent.label === 'negativ' ? 'loss' : 'neutral') : ''}</div><div class="small ${v.transcript ? '' : 'faint'}" style="white-space:pre-wrap">${v.transcript ? esc(v.transcript) : 'Keine Transkription'}</div>${v.blobId ? `<audio controls data-blob="${v.blobId}" preload="none"></audio>` : ''}</div><button type="button" class="btn ghost icon sm" data-action="delete-voice" data-trade="${t.id}" data-voice="${v.id}" aria-label="Sprachnotiz löschen">${I.trash}</button></div>`; }).join('') : '<div class="muted small">Noch keine Sprachnotizen.</div>';
    const voiceCard = U.card('Sprachnotizen', `${voice}<div class="row" style="margin-top:12px"><button type="button" class="btn sm" id="voice-rec" data-action="voice-record" data-trade="${t.id}">${I.mic} Aufnehmen</button><button type="button" class="btn sm ghost" data-action="voice-text" data-trade="${t.id}">${I.note} Text-Notiz</button><span class="small muted" id="voice-status"></span></div>`, { info: 'Aufnahme über das Mikrofon mit Transkription, wenn der Browser das erlaubt. Die Stimmung wird aus dem Text abgeleitet.' });
    const foot = `<div class="row" style="justify-content:flex-end"><button type="button" class="btn danger sm" data-action="delete-trade" data-id="${t.id}">${I.trash} Löschen</button><button type="button" class="btn primary sm" data-action="edit-trade" data-id="${t.id}">${I.edit} Bearbeiten</button></div>`;
    return `${head}<div class="grid two">${planCard}${discCard}${excCard}${tagsCard}${shotCard}${voiceCard}</div>${foot}`;
  }
  function excBar(label, v, color) { const max = 3; const w = Math.min(Math.abs(v), max) / max * 100; return `<div><div class="row between small"><span>${label}</span><b class="${color === 'loss' ? 'neg' : 'pos'}">${fmt.num(v, 2)} R</b></div><div class="exc-bar"><i style="left:0;width:${w}%;background:var(--${color});opacity:.75"></i></div></div>`; }

  App.screens.trades.mount = function (main, ctx) {
    if (!ctx.params[0]) return; const id = ctx.params[0]; const dz = main.querySelector('#shot-drop'), fi = main.querySelector('#shot-file'); if (!dz) return;
    const add = async files => { const t = S.getTrade(id); if (!t) return; let n = 0; for (const f of files) { if (!f.type.startsWith('image/')) continue; const bid = await root.Blobs.put(f).catch(() => null); if (bid) { (t.screenshots = t.screenshots || []).push(bid); n++; } } if (n) { S.save(); U.toast(`${n} Bild${n > 1 ? 'er' : ''} gespeichert`, 'ok'); App.rerender(); } else U.toast('Keine Bilder erkannt', 'err'); };
    dz.addEventListener('click', () => fi.click()); fi.addEventListener('change', () => add([...fi.files])); dz.addEventListener('dragover', e => { e.preventDefault(); dz.classList.add('over'); }); dz.addEventListener('dragleave', () => dz.classList.remove('over')); dz.addEventListener('drop', e => { e.preventDefault(); dz.classList.remove('over'); add([...e.dataTransfer.files]); });
    const onPaste = e => { if (document.querySelector('.modal-bg')) return; const files = [...(e.clipboardData?.files || [])].filter(f => f.type.startsWith('image/')); if (files.length) { e.preventDefault(); add(files); } }; document.addEventListener('paste', onPaste, { once: false }); App._pasteHandler && document.removeEventListener('paste', App._pasteHandler); App._pasteHandler = onPaste;
  };

  Object.assign(App.actions, {
    'trades-view'(el) { App.state.tradeFilter.view = el.dataset.value; App.rerender(); },
    'trade-sort'(el) { const k = el.dataset.key; const s = App.state.tradeSort; if (s.key === k) s.dir = -s.dir; else { s.key = k; s.dir = k === 'symbol' || k === 'setup' || k === 'strategy' ? 1 : -1; } App.rerender(); },
    'trade-q'(el) { App.state.tradeFilter.q = el.value; clearTimeout(App._qt); App._qt = setTimeout(() => { App.rerender(); const q = document.getElementById('tf-q'); if (q) { q.focus(); q.setSelectionRange(q.value.length, q.value.length); } }, 250); },
    'trade-filter'(el) { App.state.tradeFilter[el.dataset.key] = el.value; App.rerender(); },
    'trade-filter-reset'() { Object.assign(App.state.tradeFilter, { q: '', symbol: '', setup: '', status: '', mistake: '' }); App.rerender(); },
    'new-missed'() {
      U.modal(`<form data-action="save-missed"><div class="modal-head"><h2>Verpassten Trade notieren</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><div class="form-grid"><div class="field"><label for="m-date">Datum</label><input class="input" type="date" id="m-date" name="date" value="${C.dayKey(new Date())}" required></div><div class="field"><label for="m-symbol">Symbol</label><input class="input" id="m-symbol" name="symbol" required></div><div class="field"><span class="lbl">Richtung</span>${U.seg([[1, 'Long'], [-1, 'Short']], 1, 'set-dir')}<input type="hidden" name="direction" value="1"></div><div class="field"><label for="m-setup">Setup</label><input class="input" id="m-setup" name="setup" list="setup-list"><datalist id="setup-list">${S.data.tags.setups.map(s => `<option value="${esc(s)}">`).join('')}</datalist></div><div class="field"><label for="m-pnl">Hätte gebracht (P&L)</label><input class="input" type="number" step="any" id="m-pnl" name="pnl" inputmode="decimal"></div><div class="field"><label for="m-r">R-Multiple</label><input class="input" type="number" step="any" id="m-r" name="r" inputmode="decimal"></div><div class="field span2"><label for="m-reason">Warum nicht gehandelt?</label><input class="input" id="m-reason" name="reason" placeholder="Gezögert, Angst, nicht am Rechner …"></div></div><div class="modal-foot"><button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`);
    },
    'save-missed'(form) { const fd = new FormData(form); S.addMissed({ date: fd.get('date'), symbol: String(fd.get('symbol')).trim().toUpperCase(), direction: Number(fd.get('direction')) === -1 ? -1 : 1, setup: String(fd.get('setup') || '').trim(), pnl: Number(fd.get('pnl')) || 0, r: fd.get('r') === '' ? null : Number(fd.get('r')), reason: String(fd.get('reason') || '') }); U.closeModal(); U.toast('Notiert', 'ok'); App.rerender(); },
    'delete-missed'(el) { S.deleteMissed(el.dataset.id); App.rerender(); },
    async 'delete-shot'(el) { const t = S.getTrade(el.dataset.trade); if (!t) return; t.screenshots = (t.screenshots || []).filter(x => x !== el.dataset.blob); await root.Blobs.del(el.dataset.blob).catch(() => {}); S.save(); App.rerender(); },
    async lightbox(el) { const u = await root.Blobs.url(el.dataset.blobId); if (!u) return; const lb = document.createElement('div'); lb.className = 'lightbox'; lb.innerHTML = `<img src="${u}" alt="Screenshot">`; lb.addEventListener('click', () => lb.remove()); document.body.appendChild(lb); },
    async 'delete-voice'(el) { const t = S.getTrade(el.dataset.trade); if (!t) return; const v = (t.voiceNotes || []).find(x => x.id === el.dataset.voice); if (v && v.blobId) await root.Blobs.del(v.blobId).catch(() => {}); t.voiceNotes = (t.voiceNotes || []).filter(x => x.id !== el.dataset.voice); S.save(); App.rerender(); },
    'voice-text'(el) { const id = el.dataset.trade; U.modal(`<form data-action="save-voice-text" data-trade="${id}"><div class="modal-head"><h2>Notiz sprechen oder tippen</h2><button type="button" class="btn ghost icon" data-close aria-label="Schließen">${I.close}</button></div><div class="field"><label for="vt-text">Text</label><textarea class="input" id="vt-text" name="text" placeholder="Wie hast du dich während des Trades gefühlt?"></textarea><span class="hint">Die Stimmung wird automatisch aus dem Text abgeleitet.</span></div><div class="modal-foot"><button type="button" class="btn" data-close>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form>`, { cls: 'narrow' }); },
    'save-voice-text'(form) { const t = S.getTrade(form.dataset.trade); const text = new FormData(form).get('text').trim(); if (!t || !text) return U.closeModal(); (t.voiceNotes = t.voiceNotes || []).push({ id: C.uid(), blobId: null, transcript: text, sentiment: C.sentiment(text), createdAt: new Date().toISOString() }); S.save(); U.closeModal(); App.rerender(); },
    async 'voice-record'(el) {
      const id = el.dataset.trade; const status = document.getElementById('voice-status');
      if (App._rec) { App._rec.stop(); return; }
      if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia || !root.MediaRecorder) { U.toast('Aufnahme in diesem Browser nicht möglich. Nutze die Text-Notiz.', 'err'); return; }
      let stream; try { stream = await navigator.mediaDevices.getUserMedia({ audio: true }); } catch (e) { U.toast('Kein Mikrofonzugriff. Nutze die Text-Notiz.', 'err'); return; }
      const chunks = []; const rec = new MediaRecorder(stream); let transcript = ''; let recog = null;
      const SR = root.SpeechRecognition || root.webkitSpeechRecognition; if (SR) { try { recog = new SR(); recog.lang = 'de-DE'; recog.continuous = true; recog.interimResults = true; recog.onresult = ev => { let fin = ''; for (let i = 0; i < ev.results.length; i++) if (ev.results[i].isFinal) fin += ev.results[i][0].transcript + ' '; transcript = fin.trim(); if (status) status.textContent = 'Aufnahme läuft … ' + (transcript ? '„' + transcript.slice(-40) + '“' : ''); }; recog.onerror = () => {}; recog.start(); } catch (e) { recog = null; } }
      rec.ondataavailable = e => chunks.push(e.data);
      rec.onstop = async () => { stream.getTracks().forEach(tr => tr.stop()); if (recog) { try { recog.stop(); } catch (e) {} } await new Promise(r => setTimeout(r, 400)); const blob = new Blob(chunks, { type: rec.mimeType || 'audio/webm' }); const bid = await root.Blobs.put(blob).catch(() => null); const t = S.getTrade(id); if (t) { (t.voiceNotes = t.voiceNotes || []).push({ id: C.uid(), blobId: bid, transcript, sentiment: transcript ? C.sentiment(transcript) : null, createdAt: new Date().toISOString() }); S.save(); } App._rec = null; U.toast(transcript ? 'Sprachnotiz mit Transkript gespeichert' : 'Sprachnotiz gespeichert', 'ok'); App.rerender(); };
      rec.start(); App._rec = rec; el.innerHTML = `${I.stop} Stopp`; el.classList.add('danger'); if (status) status.textContent = recog ? 'Aufnahme läuft, Transkription aktiv …' : 'Aufnahme läuft (keine Transkription in diesem Browser)';
    },
  });
})(typeof self !== 'undefined' ? self : this);
