/* Dashboard-Widgets: zentrale Registry, Berechnungen, Diagramme und Bausteine.
   Neues Widget = ein Eintrag in TOP (oberer Bereich) oder MAIN (unterer Bereich): typ, name, desc, info, groesse, preview, render(d, inst). */
(function (root) {
  'use strict';
  const C = root.Core, S = root.Store, U = root.UI, I = U.I, esc = U.esc, fmt = U.fmt;
  const SIZES = { klein: 'Klein', mittel: 'Mittel', gross: 'Groß' };
  const MAX_TOP = 5;
  const NO_DATA = 'Noch keine Daten';

  /* ---------- gemeinsame Daten je Render (werden erst bei Bedarf berechnet) ---------- */
  function makeData(ctx, App) {
    const d = { list: ctx.inRange, all: ctx.all, account: App.account(), range: App.range() };
    const lazy = (k, fn) => Object.defineProperty(d, k, { configurable: true, enumerable: true, get() { const v = fn(); Object.defineProperty(d, k, { value: v, enumerable: true }); return v; } });
    lazy('closed', () => C.closedOnly(d.list));
    lazy('empty', () => !d.closed.length);
    lazy('s', () => C.summary(d.list));
    lazy('days', () => C.dailyAggregation(d.list));
    lazy('ds', () => C.daySummary(d.days));
    lazy('daysAll', () => C.dailyAggregation(d.all));
    lazy('streaks', () => C.streaks(d.list));
    lazy('dayStreaks', () => C.dayStreaks(d.days));
    lazy('dd', () => C.drawdownStats(d.days, d.account));
    lazy('running', () => C.runningStats(d.days));
    lazy('score', () => C.traderScore(d.list, d.account));
    return d;
  }

  /* ---------- Bausteine ---------- */
  const noData = () => `<span class="nodata">${NO_DATA}</span>`;
  const emptyBox = (h = 220) => `<div class="empty" style="min-height:${h}px">${I.stats}<b>${NO_DATA}</b><span class="small">Logge Trades oder ändere den Zeitraum.</span></div>`;
  const tile = (e, value, o = {}) => U.tile(e.name, value, Object.assign({ info: e.info }, o));
  const card = (e, body, o = {}) => U.card(e.name, body, Object.assign({ info: e.info }, o));
  const pctText = f => (f < 0 ? '−' : '') + Math.abs(f * 100).toFixed(1).replace('.', ',') + ' %';
  const streakPills = (maxW, maxL, unit) => `<span class="pills col">${U.pill(`${maxL} ${unit}`, 'loss')}${U.pill(`${maxW} ${unit}`, 'win')}</span>`;
  const streakRing = (n, kind) => `<span class="streak-ring ${kind === 'loss' ? 'loss' : 'win'}">${n}</span>`;
  const curShort = v => { const a = Math.abs(v); const s = a >= 1000 ? (a / 1000).toFixed(a >= 10000 ? 0 : 1).replace('.', ',').replace(',0', '') + 'k' : String(Math.round(a)); return (v < 0 ? '−' : '') + s; };
  const xTicks = (n, iw) => { const k = Math.max(2, Math.min(n, Math.floor(iw / 95) + 1)); if (n <= k) return Array.from({ length: n }, (_, i) => i); return Array.from({ length: k }, (_, i) => Math.round(i / (k - 1) * (n - 1))); };
  const gid = () => 'g' + Math.random().toString(36).slice(2, 8);
  const chartEmpty = el => { el.innerHTML = `<div class="empty" style="min-height:0;height:100%">${I.stats}<span class="small">${NO_DATA}</span></div>`; };
  function bindHover(el, svg, n, xf, yf, tipFn) {
    const hover = svg.querySelector('.hover'), hit = svg.querySelector('.hit'); if (!hover || !hit) return;
    const show = e => { const r = hit.getBoundingClientRect(); const cx = e.touches ? e.touches[0].clientX : e.clientX; const i = C.clamp(Math.round((cx - r.left) / r.width * (n - 1)), 0, n - 1); hover.classList.add('on'); const x = xf(i); const ln = hover.querySelector('line'); ln.setAttribute('x1', x); ln.setAttribute('x2', x); const c = hover.querySelector('circle'); if (c) { const y = yf(i); if (y == null) c.style.display = 'none'; else { c.style.display = ''; c.setAttribute('cx', x); c.setAttribute('cy', y); } } U.tipAt(el, x, yf(i) == null ? 20 : yf(i), tipFn(i)); };
    hit.addEventListener('mousemove', show); hit.addEventListener('touchstart', show, { passive: true }); hit.addEventListener('touchmove', show, { passive: true });
    hit.addEventListener('mouseleave', () => { hover.classList.remove('on'); U.tipHide(); }); hit.addEventListener('touchend', () => { hover.classList.remove('on'); U.tipHide(); });
  }
  const unitFmt = (u, v, short) => v == null || isNaN(v) ? '—' : u === 'pct' ? fmt.pct(v, short ? 0 : 1) : u === 'cur' ? (short ? curShort(v) : fmt.cur(v, { signed: true })) : u === 'int' ? fmt.int(v) : fmt.num(v, 2);

  /* ---------- Diagramme ---------- */
  /* Mehrere Linien mit bis zu zwei Achsen (verschiedene Einheiten) */
  U.drawers.lines = function (el, d, W, H) {
    const pts = d && d.points || [], series = d && d.series || []; if (pts.length < 2 || !series.length) { chartEmpty(el); return; }
    const units = [...new Set(series.map(s => s.unit))]; const two = units.length > 1; const ml = two ? 50 : 8, mr = 56, mt = 12, mb = 26; const iw = W - ml - mr, ih = H - mt - mb;
    const scale = {};
    units.forEach((u, ui) => { const vals = series.filter(s => s.unit === u).flatMap(s => pts.map(p => p.v[s.key])).filter(v => v != null && isFinite(v)); if (!vals.length) vals.push(0); const ticks = ui < 2 ? U.niceTicks(Math.min(...vals), Math.max(...vals), 4) : []; scale[u] = { ticks, y0: Math.min(ticks[0] == null ? Infinity : ticks[0], ...vals), y1: Math.max(ticks[ticks.length - 1] == null ? -Infinity : ticks[ticks.length - 1], ...vals) }; });
    const x = i => ml + i / (pts.length - 1) * iw; const y = (u, v) => mt + (scale[u].y1 - v) / (scale[u].y1 - scale[u].y0 || 1) * ih;
    const path = s => { let out = '', open = false; pts.forEach((p, i) => { const v = p.v[s.key]; if (v == null || !isFinite(v)) { open = false; return; } out += `${open ? 'L' : 'M'}${x(i).toFixed(1)},${y(s.unit, v).toFixed(1)}`; open = true; }); return out; };
    const u0 = units[0], u1 = units[1]; const xt = xTicks(pts.length, iw);
    el.innerHTML = `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"><g class="grid">${scale[u0].ticks.map(t => `<line x1="${ml}" x2="${W - mr}" y1="${y(u0, t)}" y2="${y(u0, t)}"/><text x="${W - mr + 8}" y="${y(u0, t) + 3.5}">${unitFmt(u0, t, true)}</text>`).join('')}${u1 ? scale[u1].ticks.map(t => `<text x="${ml - 8}" y="${y(u1, t) + 3.5}" text-anchor="end">${unitFmt(u1, t, true)}</text>`).join('') : ''}</g>
      ${series.map(s => `<path d="${path(s)}" fill="none" stroke="${s.color}" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>`).join('')}
      ${xt.map(i => `<text x="${x(i)}" y="${H - 7}" text-anchor="${i === 0 ? 'start' : i === pts.length - 1 ? 'end' : 'middle'}">${fmt.date(pts[i].date)}</text>`).join('')}
      <g class="hover"><line y1="${mt}" y2="${H - mb}" stroke="var(--text-2)" stroke-opacity=".5"/></g><rect class="hit" x="${ml}" y="0" width="${iw}" height="${H}" fill="transparent"/></svg>`;
    bindHover(el, el.firstElementChild, pts.length, x, () => null, i => `<b>${fmt.weekdayLong(pts[i].date)}</b>${series.map(s => `<br><i class="dot" style="background:${s.color}"></i>${esc(s.label)}: ${unitFmt(s.unit, pts[i].v[s.key])}`).join('')}`);
  };
  /* Punktdiagramm (Uhrzeit, Haltedauer) */
  U.drawers.scatter = function (el, d, W, H) {
    const pts = d && d.points || []; if (!pts.length) { chartEmpty(el); return; }
    const ml = 8, mr = 56, mt = 12, mb = 30; const iw = W - ml - mr, ih = H - mt - mb;
    const xs = pts.map(p => p.x); const x0 = d.x0 != null ? d.x0 : Math.min(...xs), x1 = d.x1 != null ? d.x1 : Math.max(...xs);
    const ys = pts.map(p => p.y); const ticks = U.niceTicks(Math.min(0, ...ys), Math.max(0, ...ys), 4); const y0 = Math.min(ticks[0], ...ys, 0), y1 = Math.max(ticks[ticks.length - 1], ...ys, 0);
    const x = v => ml + (v - x0) / (x1 - x0 || 1) * iw, y = v => mt + (y1 - v) / (y1 - y0 || 1) * ih;
    const xt = (d.xTicks || []).filter(t => t.v >= x0 && t.v <= x1);
    el.innerHTML = `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"><g class="grid">${ticks.map(t => `<line x1="${ml}" x2="${W - mr}" y1="${y(t)}" y2="${y(t)}"/><text x="${W - mr + 8}" y="${y(t) + 3.5}">${curShort(t)}</text>`).join('')}</g><line class="zero" x1="${ml}" x2="${W - mr}" y1="${y(0)}" y2="${y(0)}"/>
      ${xt.map(t => `<text x="${x(t.v)}" y="${H - 8}" text-anchor="middle">${esc(t.label)}</text>`).join('')}
      ${pts.map(p => `<circle cx="${x(p.x).toFixed(1)}" cy="${y(p.y).toFixed(1)}" r="3.6" fill="var(--${p.y > C.EPS ? 'profit' : p.y < -C.EPS ? 'loss' : 'be'})" fill-opacity=".85" data-tip="${esc(p.tip)}"></circle>`).join('')}</svg>`;
  };
  /* Säulen je Handelstag */
  U.drawers.dbars = function (el, d, W, H) {
    const days = d && d.days || []; if (!days.length) { chartEmpty(el); return; }
    const ml = 8, mr = 56, mt = 12, mb = 26; const iw = W - ml - mr, ih = H - mt - mb; const vals = days.map(x => x.pnl);
    const ticks = U.niceTicks(Math.min(0, ...vals), Math.max(0, ...vals), 4); const y0 = Math.min(ticks[0], ...vals, 0), y1 = Math.max(ticks[ticks.length - 1], ...vals, 0);
    const n = days.length; const gap = iw / n; const bw = Math.max(2, Math.min(18, gap * 0.62)); const x = i => ml + i * gap + gap / 2, y = v => mt + (y1 - v) / (y1 - y0 || 1) * ih; const xt = xTicks(n, iw);
    el.innerHTML = `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"><g class="grid">${ticks.map(t => `<line x1="${ml}" x2="${W - mr}" y1="${y(t)}" y2="${y(t)}"/><text x="${W - mr + 8}" y="${y(t) + 3.5}">${curShort(t)}</text>`).join('')}</g><line class="zero" x1="${ml}" x2="${W - mr}" y1="${y(0)}" y2="${y(0)}"/>
      ${days.map((p, i) => `<rect x="${(x(i) - bw / 2).toFixed(1)}" y="${Math.min(y(p.pnl), y(0)).toFixed(1)}" width="${bw.toFixed(1)}" height="${Math.max(1.5, Math.abs(y(p.pnl) - y(0))).toFixed(1)}" rx="2" fill="var(--${p.pnl >= 0 ? 'profit' : 'loss'})" fill-opacity=".85" data-tip="<b>${fmt.weekdayLong(p.day)}</b><br>${fmt.cur(p.pnl, { signed: true })} · ${p.n} Trade${p.n === 1 ? '' : 's'}"></rect>`).join('')}
      ${xt.map(i => `<text x="${x(i)}" y="${H - 7}" text-anchor="${i === 0 ? 'start' : i === n - 1 ? 'end' : 'middle'}">${fmt.date(days[i].day)}</text>`).join('')}</svg>`;
  };
  /* Drawdown-Fläche */
  U.drawers.dd = function (el, d, W, H) {
    const pts = d && d.points || []; if (!pts.length) { chartEmpty(el); return; }
    const ml = 8, mr = 56, mt = 12, mb = 26; const iw = W - ml - mr, ih = H - mt - mb; const vals = pts.map(p => p.dd);
    const ticks = U.niceTicks(Math.min(...vals, -1), 0, 4); const y0 = Math.min(ticks[0], ...vals), y1 = 0; const n = pts.length;
    const x = i => n === 1 ? ml + iw / 2 : ml + i / (n - 1) * iw, y = v => mt + (y1 - v) / (y1 - y0 || 1) * ih; const g = gid();
    const line = n === 1 ? `M${x(0) - 1},${y(pts[0].dd)}L${x(0) + 1},${y(pts[0].dd)}` : 'M' + pts.map((p, i) => `${x(i).toFixed(1)},${y(p.dd).toFixed(1)}`).join('L'); const xt = xTicks(n, iw);
    el.innerHTML = `<svg viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"><defs><linearGradient id="${g}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--loss)" stop-opacity=".05"/><stop offset="1" stop-color="var(--loss)" stop-opacity=".45"/></linearGradient></defs><g class="grid">${ticks.map(t => `<line x1="${ml}" x2="${W - mr}" y1="${y(t)}" y2="${y(t)}"/><text x="${W - mr + 8}" y="${y(t) + 3.5}">${curShort(t)}</text>`).join('')}</g>
      <path d="${line} L${x(n - 1)},${y(0)} L${x(0)},${y(0)} Z" fill="url(#${g})"/><path d="${line}" fill="none" stroke="var(--loss)" stroke-width="2" stroke-linejoin="round"/>
      ${xt.map(i => `<text x="${x(i)}" y="${H - 7}" text-anchor="${i === 0 ? 'start' : i === n - 1 ? 'end' : 'middle'}">${fmt.date(pts[i].date)}</text>`).join('')}
      <g class="hover"><line y1="${mt}" y2="${H - mb}" stroke="var(--text-2)" stroke-opacity=".5"/><circle r="4.5" fill="var(--loss)" stroke="var(--surface)" stroke-width="2"/></g><rect class="hit" x="${ml}" y="0" width="${iw}" height="${H}" fill="transparent"/></svg>`;
    bindHover(el, el.firstElementChild, n, x, i => y(pts[i].dd), i => `<b>${fmt.weekdayLong(pts[i].date)}</b><br>Drawdown: ${U.pnl(pts[i].dd)}<br><span class="muted">Kumuliert: ${fmt.cur(pts[i].cum, { signed: true })}</span>`);
  };

  /* ---------- Kalender-Bausteine ---------- */
  function calendarHTML(days, year, month, o = {}) {
    const weeks = C.calendarMonth(days, year, month); const today = C.dayKey(new Date()); const ext = !!o.weeks, mini = !!o.mini;
    let html = C.WEEKDAYS.map(w => `<div class="wd">${w}</div>`).join('') + (ext ? '<div class="wd wk">Woche</div>' : '');
    for (const wk of weeks) {
      html += wk.cells.map(c => { if (!c) return '<div class="d pad"></div>'; const e = c.entry; const k = e ? (e.pnl > C.EPS ? 'win' : e.pnl < -C.EPS ? 'loss' : 'be') : ''; return `<div class="d ${k} ${c.key === today ? 'today' : ''}" data-action="day" data-day="${c.key}" role="button" tabindex="0" ${mini && e ? `data-tip="<b>${fmt.dateFull(c.date)}</b><br>${fmt.cur(e.pnl, { signed: true })} · ${e.n} Trade${e.n === 1 ? '' : 's'}"` : ''}><span class="n">${c.date.getDate()}</span>${e && !mini ? `<span class="p ${U.cls(e.pnl)}">${fmt.cur(e.pnl, { signed: true, compact: Math.abs(e.pnl) >= 1000 })}</span><span class="c">${e.n} Trade${e.n === 1 ? '' : 's'}</span>` : ''}</div>`; }).join('');
      if (ext) html += `<div class="w"><span class="t">Woche ${wk.index}</span>${wk.days ? `<span class="p ${U.cls(wk.pnl)}">${fmt.cur(wk.pnl, { signed: true, compact: Math.abs(wk.pnl) >= 1000 })}</span><span class="days">${wk.days} Tag${wk.days === 1 ? '' : 'e'}</span>` : '<span class="p muted">—</span>'}</div>`;
    }
    return `<div class="cal ${ext ? 'ext' : ''} ${mini ? 'mini' : ''}">${html}</div>`;
  }
  const monthSub = (days, m) => { const inM = days.filter(d => d.day.getFullYear() === m.getFullYear() && d.day.getMonth() === m.getMonth()); const total = C.sum(inM.map(d => d.pnl)); return inM.length ? `<b class="${U.cls(total)}">${fmt.cur(total, { signed: true })}</b> · ${inM.length} Handelstage` : '<span class="muted">Keine Trades</span>'; };
  const calNav = (m, prevA, nextA, todayA, extra = '') => `<div class="cal-nav"><button type="button" class="btn round" data-action="${prevA}" aria-label="Voriger Monat">${I.chevL}</button><h3 style="font-size:15px;min-width:140px;text-align:center">${fmt.monthYear(m)}</h3><button type="button" class="btn round" data-action="${nextA}" aria-label="Nächster Monat">${I.chevR}</button>${todayA ? `<button type="button" class="btn sm hide-m" data-action="${todayA}">Heute</button>` : ''}${extra}</div>`;
  function yearHTML(days, year) {
    const map = new Map(days.map(d => [d.key, d])); const today = C.dayKey(new Date()); const total = C.sum(days.filter(d => d.day.getFullYear() === year).map(d => d.pnl));
    const months = Array.from({ length: 12 }, (_, m) => {
      const first = new Date(year, m, 1), count = new Date(year, m + 1, 0).getDate(); const lead = (first.getDay() + 6) % 7; let cells = ''; let mp = 0, mn = 0;
      for (let i = 0; i < lead; i++) cells += '<i class="pad"></i>';
      for (let i = 1; i <= count; i++) { const dt = new Date(year, m, i); const k = C.dayKey(dt); const e = map.get(k); if (e) { mp += e.pnl; mn += e.n; } const cl = e ? (e.pnl > C.EPS ? 'win' : e.pnl < -C.EPS ? 'loss' : 'be') : ''; cells += `<i class="${cl} ${k === today ? 'today' : ''}" data-action="day" data-day="${k}" ${e ? `data-tip="<b>${fmt.dateFull(dt)}</b><br>${fmt.cur(e.pnl, { signed: true })} · ${e.n} Trade${e.n === 1 ? '' : 's'}"` : ''}></i>`; }
      return `<div class="ym"><div class="ym-head"><b>${first.toLocaleDateString('de-DE', { month: 'long' })}</b><span class="${mn ? U.cls(mp) : 'muted'}">${mn ? fmt.cur(mp, { signed: true, compact: Math.abs(mp) >= 1000 }) : '—'}</span></div><div class="ym-grid">${cells}</div></div>`;
    }).join('');
    return `<div class="year-grid">${months}</div><div class="small muted" style="margin-top:10px">Jahr ${year}: <b class="${U.cls(total)}">${fmt.cur(total, { signed: true })}</b></div>`;
  }

  /* ---------- Vorschaubilder für die Widget-Bibliothek ---------- */
  const PV = {
    num: '<rect x="8" y="10" width="30" height="6" rx="3" fill="var(--faint)"/><rect x="8" y="24" width="52" height="14" rx="4" fill="var(--text-2)"/><rect x="8" y="46" width="22" height="5" rx="2.5" fill="var(--faint)"/>',
    gauge: '<rect x="8" y="10" width="30" height="6" rx="3" fill="var(--faint)"/><rect x="8" y="24" width="30" height="12" rx="4" fill="var(--text-2)"/><path d="M56 48a18 18 0 0 1 36 0" fill="none" stroke="var(--surface-3)" stroke-width="7"/><path d="M56 48a18 18 0 0 1 22-17.5" fill="none" stroke="var(--profit)" stroke-width="7"/>',
    donut: '<rect x="8" y="10" width="30" height="6" rx="3" fill="var(--faint)"/><rect x="8" y="24" width="30" height="12" rx="4" fill="var(--text-2)"/><circle cx="74" cy="34" r="16" fill="none" stroke="var(--loss)" stroke-width="7"/><path d="M74 18a16 16 0 0 1 14 24" fill="none" stroke="var(--profit)" stroke-width="7"/>',
    wl: '<rect x="8" y="10" width="30" height="6" rx="3" fill="var(--faint)"/><rect x="8" y="24" width="24" height="12" rx="4" fill="var(--text-2)"/><rect x="48" y="26" width="44" height="7" rx="3.5" fill="var(--loss)"/><rect x="48" y="26" width="28" height="7" rx="3.5" fill="var(--profit)"/>',
    streak: '<rect x="8" y="10" width="30" height="6" rx="3" fill="var(--faint)"/><circle cx="26" cy="38" r="13" fill="none" stroke="var(--profit)" stroke-width="4"/><rect x="48" y="28" width="30" height="7" rx="3.5" fill="var(--loss-soft)"/><rect x="48" y="40" width="30" height="7" rx="3.5" fill="var(--accent-soft)"/>',
    radar: '<polygon points="50,8 86,30 76,58 24,58 14,30" fill="none" stroke="var(--border-2)"/><polygon points="50,20 74,32 68,52 32,52 26,32" fill="none" stroke="var(--border-2)"/><polygon points="50,14 70,34 62,52 38,48 30,34" fill="var(--accent)" fill-opacity=".3" stroke="var(--accent)" stroke-width="1.5"/>',
    area: '<path d="M8 50 L24 38 L38 44 L52 26 L66 30 L80 14 L92 20 L92 56 L8 56 Z" fill="var(--profit)" fill-opacity=".25"/><path d="M8 50 L24 38 L38 44 L52 26 L66 30 L80 14 L92 20" fill="none" stroke="var(--profit)" stroke-width="2"/>',
    line: '<path d="M8 44 L24 30 L38 36 L52 20 L66 26 L80 14 L92 18" fill="none" stroke="var(--accent)" stroke-width="2"/><path d="M8 30 L24 34 L38 28 L52 36 L66 30 L80 34 L92 28" fill="none" stroke="var(--loss)" stroke-width="2"/><path d="M8 20 L24 22 L38 18 L52 24 L66 18 L80 22 L92 24" fill="none" stroke="var(--be)" stroke-width="2"/>',
    scatter: '<line x1="8" x2="92" y1="34" y2="34" stroke="var(--border-2)" stroke-dasharray="3 3"/>' + [[16, 22, 'profit'], [24, 40, 'loss'], [32, 18, 'profit'], [40, 30, 'profit'], [48, 46, 'loss'], [56, 26, 'profit'], [64, 38, 'loss'], [72, 14, 'profit'], [80, 30, 'profit'], [88, 44, 'loss']].map(([x, y, c]) => `<circle cx="${x}" cy="${y}" r="3" fill="var(--${c})"/>`).join(''),
    bars: [[10, 20, 'profit'], [20, 12, 'profit'], [30, -10, 'loss'], [40, 26, 'profit'], [50, -18, 'loss'], [60, 8, 'profit'], [70, -6, 'loss'], [80, 22, 'profit'], [90, 14, 'profit']].map(([x, h, c]) => `<rect x="${x - 3}" y="${h > 0 ? 34 - h : 34}" width="6" height="${Math.abs(h)}" rx="1.5" fill="var(--${c})"/>`).join('') + '<line x1="6" x2="94" y1="34" y2="34" stroke="var(--border-2)"/>',
    combo: '<path d="M8 46 L26 40 L44 44 L62 22 L80 26 L92 12 L92 56 L8 56 Z" fill="var(--profit)" fill-opacity=".2"/><path d="M8 46 L26 40 L44 44 L62 22 L80 26 L92 12" fill="none" stroke="var(--profit)" stroke-width="2"/>' + [[14, 8, 'profit'], [26, -6, 'loss'], [38, 10, 'profit'], [50, -12, 'loss'], [62, 14, 'profit'], [74, 6, 'profit'], [86, -8, 'loss']].map(([x, h, c]) => `<rect x="${x - 2.5}" y="${h > 0 ? 44 - h : 44}" width="5" height="${Math.abs(h)}" fill="var(--${c})" fill-opacity=".8"/>`).join(''),
    table: [12, 24, 36, 48].map(y => `<rect x="8" y="${y}" width="36" height="5" rx="2.5" fill="var(--faint)"/><rect x="52" y="${y}" width="18" height="5" rx="2.5" fill="var(--text-2)"/><rect x="76" y="${y}" width="16" height="5" rx="2.5" fill="var(--${y % 24 ? 'loss' : 'profit'})"/>`).join(''),
    calendar: Array.from({ length: 21 }, (_, i) => { const x = 10 + (i % 7) * 12, y = 12 + Math.floor(i / 7) * 14; const c = [1, 3, 8, 9, 11, 15, 17, 19].includes(i) ? 'profit' : [2, 6, 12, 16].includes(i) ? 'loss' : 'surface-3'; return `<rect x="${x}" y="${y}" width="10" height="11" rx="2" fill="var(--${c})" fill-opacity="${c === 'surface-3' ? 1 : .8}"/>`; }).join(''),
    calext: Array.from({ length: 21 }, (_, i) => { const x = 8 + (i % 7) * 10, y = 12 + Math.floor(i / 7) * 14; const c = [1, 3, 8, 9, 11, 15, 17, 19].includes(i) ? 'profit' : [2, 6, 12, 16].includes(i) ? 'loss' : 'surface-3'; return `<rect x="${x}" y="${y}" width="8" height="11" rx="2" fill="var(--${c})"/>`; }).join('') + [12, 26, 40].map((y, i) => `<rect x="80" y="${y}" width="12" height="11" rx="2" fill="var(--${i === 1 ? 'loss' : 'profit'})" fill-opacity=".5"/>`).join(''),
    year: Array.from({ length: 12 }, (_, i) => { const x = 8 + (i % 6) * 14.5, y = 12 + Math.floor(i / 6) * 24; return `<rect x="${x}" y="${y}" width="12" height="18" rx="2" fill="var(--${[0, 2, 3, 5, 8, 10].includes(i) ? 'profit' : [1, 6, 9].includes(i) ? 'loss' : 'surface-3'})" fill-opacity=".7"/>`; }).join(''),
    heat: Array.from({ length: 35 }, (_, i) => { const x = 8 + Math.floor(i / 5) * 12.5, y = 10 + (i % 5) * 10; const l = [0, .2, .45, .7, 1][(i * 7) % 5]; return `<rect x="${x}" y="${y}" width="9" height="8" rx="2" fill="var(--accent)" fill-opacity="${l || .08}"/>`; }).join(''),
    progress: '<rect x="8" y="14" width="40" height="5" rx="2.5" fill="var(--faint)"/><rect x="8" y="24" width="84" height="8" rx="4" fill="var(--surface-3)"/><rect x="8" y="24" width="56" height="8" rx="4" fill="var(--profit)"/><rect x="8" y="40" width="30" height="5" rx="2.5" fill="var(--faint)"/><rect x="8" y="50" width="84" height="8" rx="4" fill="var(--surface-3)"/><rect x="8" y="50" width="24" height="8" rx="4" fill="var(--loss)"/>',
    dd: '<line x1="8" x2="92" y1="12" y2="12" stroke="var(--border-2)"/><path d="M8 12 L20 28 L32 16 L44 40 L56 30 L68 12 L80 34 L92 22 L92 12 Z" fill="var(--loss)" fill-opacity=".3"/><path d="M8 12 L20 28 L32 16 L44 40 L56 30 L68 12 L80 34 L92 22" fill="none" stroke="var(--loss)" stroke-width="2"/>',
  };
  const preview = kind => `<svg viewBox="0 0 100 64" width="96" height="62" aria-hidden="true">${PV[kind] || PV.num}</svg>`;

  /* ---------- Oberer Bereich: Kennzahl-Kacheln ---------- */
  const TOP = [
    { typ: 'netto_pnl', name: 'Netto P&L', preview: 'num', desc: 'Realisierter Netto-Gewinn oder -Verlust aller geschlossenen Trades, mit Anzahl der Trades.', info: 'Summe der Netto-Ergebnisse (nach Gebühren) aller geschlossenen Trades im gewählten Zeitraum. Rechts die Anzahl der Trades.',
      render(d, inst, e) { return tile(e, d.empty ? noData() : U.pnl(d.s.total, '', { signed: false }), { n: d.empty ? null : `${d.s.n} Trade${d.s.n === 1 ? '' : 's'}`, foot: d.empty ? '' : `Ø ${fmt.cur(d.s.expectancy, { signed: true })} pro Trade` }); } },
    { typ: 'kontostand_pnl', name: 'Kontostand & P&L', preview: 'num', desc: 'Aktueller Kontostand (Startkapital plus Netto-P&L) und Gesamt-P&L.', info: 'Kontogröße aus den Einstellungen plus Netto-P&L des Zeitraums. Darunter der Gesamt-P&L.',
      render(d, inst, e) { return tile(e, d.empty ? noData() : fmt.cur(d.account + d.s.total), { foot: d.empty ? '' : `P&L: ${U.pnl(d.s.total)}` }); } },
    { typ: 'trade_trefferquote', name: 'Trade-Trefferquote', preview: 'gauge', desc: 'Anteil der Gewinn-Trades an allen Trades, als Halbkreis mit Gewinnern, Breakeven und Verlierern.', info: 'Gewinn-Trades geteilt durch alle geschlossenen Trades. Break-even-Trades zählen nicht als Gewinn.',
      render(d, inst, e) { const s = d.s; return tile(e, d.empty ? noData() : fmt.pct(s.winRate, 1), d.empty ? {} : { gauge: U.semiGauge([{ v: s.wins, c: 'profit' }, { v: s.be, c: 'be' }, { v: s.losses, c: 'loss' }], ''), foot: `<span class="pills">${U.pill(s.wins, 'win')}${U.pill(s.be, 'be')}${U.pill(s.losses, 'loss')}</span>` }); } },
    { typ: 'profit_faktor', name: 'Profit-Faktor', preview: 'donut', desc: 'Summe aller Gewinne geteilt durch Summe aller Verluste, als Ring-Diagramm.', info: 'Bruttogewinn geteilt durch Bruttoverlust. Über 1,5 gilt als gut, unter 1 ist das Konto langfristig im Minus.',
      render(d, inst, e) { const s = d.s; return tile(e, d.empty ? noData() : fmt.factor(s.pf), d.empty ? {} : { gauge: U.donut([{ v: s.gp, c: 'profit' }, { v: -s.gl, c: 'loss' }], 58, 8), foot: `${fmt.cur(s.gp, { compact: true })} / ${fmt.cur(s.gl, { compact: true })}` }); } },
    { typ: 'tages_trefferquote', name: 'Tages-Trefferquote', preview: 'gauge', desc: 'Gewinntage geteilt durch alle Handelstage.', info: 'Anteil der Handelstage mit positivem Netto-Ergebnis an allen Handelstagen im Zeitraum.',
      render(d, inst, e) { const ds = d.ds; const be = ds.days - ds.winDays - ds.lossDays; return tile(e, d.empty ? noData() : fmt.pct(ds.dayWinRate, 1), d.empty ? {} : { gauge: U.semiGauge([{ v: ds.winDays, c: 'profit' }, { v: be, c: 'be' }, { v: ds.lossDays, c: 'loss' }], ''), foot: `<span class="pills">${U.pill(ds.winDays, 'win')}${U.pill(be, 'be')}${U.pill(ds.lossDays, 'loss')}</span>` }); } },
    { typ: 'avg_gewinn_verlust', name: 'Ø Gewinn / Ø Verlust', preview: 'wl', desc: 'Durchschnittlicher Gewinn und Verlust pro Trade als Balken im Verhältnis zueinander.', info: 'Durchschnittlicher Gewinn-Trade geteilt durch durchschnittlichen Verlust-Trade. Der Balken zeigt das Verhältnis.',
      render(d, inst, e) { const s = d.s; const wf = s.avgWin / (s.avgWin - s.avgLoss || 1) * 100; return tile(e, d.empty ? noData() : (s.payoff == null ? (s.avgWin > 0 ? '∞' : '—') : fmt.num(s.payoff, 2)), d.empty ? {} : { gauge: `<div class="wl-single"><div class="track"><i style="width:${wf}%;background:var(--profit)"></i><i style="flex:1;background:var(--loss)"></i></div><div class="lbl"><span class="pos">${fmt.cur(s.avgWin, { compact: s.avgWin >= 1000 })}</span><span class="neg">${fmt.cur(s.avgLoss, { compact: -s.avgLoss >= 1000 })}</span></div></div>` }).replace('class="tile"', 'class="tile wide"'); } },
    { typ: 'erwartungswert', name: 'Erwartungswert pro Trade', preview: 'num', desc: '(Trefferquote × Ø Gewinn) − (Verlustquote × Ø Verlust).', info: 'Trefferquote × Ø Gewinn minus Verlustquote × Ø Verlust. Was ein Trade im Schnitt einbringt.',
      render(d, inst, e) { const s = d.s; return tile(e, d.empty ? noData() : U.pnl(s.tradeExpectancy), { foot: d.empty ? '' : `${fmt.pct(s.winRate)} × ${fmt.cur(s.avgWin, { compact: true })} − ${fmt.pct(s.lossRate)} × ${fmt.cur(-s.avgLoss, { compact: true })}` }); } },
    { typ: 'tages_serie', name: 'Aktuelle Tages-Serie', preview: 'streak', desc: 'Gewinntage oder Verlusttage in Folge.', info: 'Handelstage in Folge mit gleichem Vorzeichen. Rot bei Verlusttagen, grün bei Gewinntagen. Die Pillen zeigen die längste Verlust- und Gewinnserie.',
      render(d, inst, e) { const st = d.dayStreaks; return tile(e, d.empty || !st.current ? noData() : `<span class="${st.kind === 'loss' ? 'neg' : 'pos'}">${st.current} Tag${st.current === 1 ? '' : 'e'}</span>`, d.empty ? {} : { gauge: streakPills(st.maxWin, st.maxLoss, 'Tage'), foot: st.current ? (st.kind === 'loss' ? 'Verlusttage in Folge' : 'Gewinntage in Folge') : '' }); } },
    { typ: 'trade_serie', name: 'Aktuelle Trade-Serie', preview: 'streak', desc: 'Gewinn-Trades oder Verlust-Trades in Folge.', info: 'Geschlossene Trades in Folge mit gleichem Ergebnis. Break-even-Trades werden übersprungen. Die Pillen zeigen die längste Verlust- und Gewinnserie.',
      render(d, inst, e) { const st = d.streaks; return tile(e, d.empty || !st.current ? noData() : `<span class="${st.kind === 'loss' ? 'neg' : 'pos'}">${st.current} Trade${st.current === 1 ? '' : 's'}</span>`, d.empty ? {} : { gauge: streakPills(st.maxWin, st.maxLoss, 'Trades'), foot: st.current ? (st.kind === 'loss' ? 'Verluste in Folge' : 'Gewinne in Folge') : '' }); } },
    { typ: 'serie', name: 'Aktuelle Serie', preview: 'streak', desc: 'Tages- und Trade-Serie kombiniert.', info: 'Links die aktuelle Tages-Serie, rechts die aktuelle Trade-Serie. Rot bei Verlusten, grün bei Gewinnen. Die Pillen zeigen jeweils die längste Verlust- und Gewinnserie.',
      render(d, inst, e) { const ds = d.dayStreaks, ts = d.streaks; return U.tile(e.name, d.empty ? noData() : `<div class="serie"><div><div class="caption">Tage</div><div class="row">${streakRing(ds.current, ds.kind)}${streakPills(ds.maxWin, ds.maxLoss, 'Tage')}</div></div><div><div class="caption">Trades</div><div class="row">${streakRing(ts.current, ts.kind)}${streakPills(ts.maxWin, ts.maxLoss, 'Trades')}</div></div></div>`, { info: e.info }); } },
    { typ: 'max_drawdown', name: 'Maximaler Drawdown', preview: 'num', desc: 'Größter Rückgang vom Höchststand, in Währung und Prozent, mit Datum.', info: 'Größter Rückgang der kumulierten Ergebniskurve von einem Hoch bis zum folgenden Tief, in Währung und in Prozent des Kontostands am Hoch.',
      render(d, inst, e) { const dd = d.dd; return tile(e, d.empty ? noData() : `<span class="neg">${fmt.cur(dd.max)}</span><small class="neg sub">${pctText(dd.maxPct)}</small>`, { foot: d.empty ? '' : dd.maxAt ? fmt.dateFull(dd.maxAt) : 'Kein Drawdown' }); } },
    { typ: 'avg_drawdown', name: 'Durchschnittlicher Drawdown', preview: 'num', desc: 'Durchschnittlicher Rückgang vom Höchststand im gewählten Zeitraum.', info: 'Mittelwert aller Drawdown-Phasen (vom Hoch bis zum tiefsten Punkt) im Zeitraum. Darunter der aktuelle Abstand zum Hoch.',
      render(d, inst, e) { const dd = d.dd; return tile(e, d.empty ? noData() : `<span class="neg">${fmt.cur(dd.avg)}</span><small class="neg sub">${pctText(dd.avgPct)}</small>`, { foot: d.empty ? '' : `Aktuell${dd.currentAt ? ` (${fmt.dateFull(dd.currentAt)})` : ''}: <span class="${U.cls(dd.current)}">${fmt.cur(dd.current)}</span>` }); } },
  ];

  /* ---------- Unterer Bereich: Diagramme, Kalender, Listen ---------- */
  const HOLD_TICKS = [[1, '1 min'], [5, '5 min'], [15, '15 min'], [30, '30 min'], [60, '1 h'], [120, '2 h'], [240, '4 h'], [480, '8 h'], [1440, '1 T'], [4320, '3 T'], [10080, '1 W']];
  const REPORT_METRICS = { netto_pnl: { label: 'Netto-P&L (kumuliert)', unit: 'cur', key: 'cum' }, tages_pnl: { label: 'Tages-P&L', unit: 'cur', key: 'dayPnl' }, trefferquote: { label: 'Trefferquote', unit: 'pct', key: 'winRate' }, profit_faktor: { label: 'Profit-Faktor', unit: 'num', key: 'pf' }, avg_gewinn: { label: 'Ø Gewinn', unit: 'cur', key: 'avgWin' }, avg_verlust: { label: 'Ø Verlust', unit: 'cur', key: 'avgLoss' }, erwartungswert: { label: 'Erwartungswert', unit: 'cur', key: 'expectancy' }, payoff: { label: 'Ø Gewinn/Verlust', unit: 'num', key: 'payoff' }, drawdown: { label: 'Drawdown', unit: 'cur', key: 'dd' }, trades: { label: 'Trades pro Tag', unit: 'int', key: 'dayN' } };
  const LINE_COLORS = ['var(--accent)', 'var(--loss)', 'var(--be)'];
  const MAIN = [
    { typ: 'score', name: 'Gesamt-Score', preview: 'radar', groesse: 'klein', desc: 'Punktzahl von 0 bis 100 aus Trefferquote, Profit-Faktor, Gewinn/Verlust-Verhältnis, Drawdown und Konstanz, als Netz-Diagramm.', info: 'Sechs Achsen von 0 bis 100: Trefferquote, Profit-Faktor, Gewinn/Verlust-Verhältnis, Konsistenz, Regeltreue und Drawdown. Der Score ist der Mittelwert.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox()); const sc = d.score; return card(e, `${U.radar(sc.axes, 230)}<div class="row" style="gap:16px;margin-top:8px;align-items:center"><div><div class="caption">Dein Score</div><div class="score-big" style="color:${U.scoreColor(sc.overall)}">${sc.overall}</div></div><div class="grow score-scale" style="margin:0 8px 14px"><div class="track"></div><div class="knob" style="left:${sc.overall}%"></div><div class="lbls"><span>0</span><span>20</span><span>40</span><span>60</span><span>80</span><span>100</span></div></div></div>`); } },
    { typ: 'kum_pnl', name: 'Kumulierter Tages-P&L', preview: 'area', groesse: 'klein', desc: 'Wie sich der Netto-P&L über die Zeit aufsummiert, als Flächendiagramm.', info: 'Kumuliertes Netto-Tagesergebnis im Zeitraum. Grün über Null, rot darunter.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); U.chartData['dash-kum_pnl'] = { days: d.days, bars: false }; return card(e, `<div class="chart h280" data-chart="pnl" data-id="dash-kum_pnl"></div>`); } },
    { typ: 'verlauf_trefferquote', name: 'Trefferquote – Ø Gewinn – Ø Verlust', preview: 'line', groesse: 'klein', desc: 'Wie sich Trefferquote, Ø Gewinn und Ø Verlust über die Handelstage entwickeln.', info: 'Laufende Werte bis zum jeweiligen Handelstag: Trefferquote (rechte Achse), Ø Gewinn und Ø Verlust (linke Achse).',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); U.chartData['dash-verlauf'] = { points: d.running.map(r => ({ date: r.date, v: { avgWin: r.avgWin, avgLoss: r.avgLoss, winRate: r.winRate } })), series: [{ key: 'avgWin', label: 'Ø Gewinn', unit: 'cur', color: 'var(--profit)' }, { key: 'avgLoss', label: 'Ø Verlust', unit: 'cur', color: 'var(--loss)' }, { key: 'winRate', label: 'Trefferquote', unit: 'pct', color: 'var(--be)' }] }; return card(e, `<div class="chart h240" data-chart="lines" data-id="dash-verlauf"></div><div class="legend"><span><i style="background:var(--profit)"></i>Ø Gewinn</span><span><i style="background:var(--loss)"></i>Ø Verlust</span><span><i style="background:var(--be)"></i>Trefferquote</span></div>`); } },
    { typ: 'perf_uhrzeit', name: 'Performance nach Uhrzeit', preview: 'scatter', groesse: 'klein', desc: 'Punktdiagramm: Uhrzeit des Einstiegs gegen P&L.', info: 'Jeder Punkt ist ein geschlossener Trade: waagerecht die Uhrzeit des Einstiegs, senkrecht das Netto-Ergebnis.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); const pts = d.closed.map(t => ({ x: t.open.getHours() * 60 + t.open.getMinutes(), y: t.pnl, tip: `<b>${esc(t.symbol)}</b> ${fmt.time(t.open)}<br>${fmt.cur(t.pnl, { signed: true })}` })); const xs = pts.map(p => p.x); const x0 = Math.floor(Math.min(...xs) / 60) * 60, x1 = Math.ceil((Math.max(...xs) + 1) / 60) * 60; const step = x1 - x0 > 12 * 60 ? 180 : x1 - x0 > 6 * 60 ? 120 : 60; const xTicksL = []; for (let m = x0; m <= x1; m += step) xTicksL.push({ v: m, label: `${String(Math.floor(m / 60)).padStart(2, '0')}:00` }); U.chartData['dash-uhrzeit'] = { points: pts, x0, x1, xTicks: xTicksL }; return card(e, `<div class="chart h280" data-chart="scatter" data-id="dash-uhrzeit"></div>`); } },
    { typ: 'perf_haltedauer', name: 'Performance nach Haltedauer', preview: 'scatter', groesse: 'klein', desc: 'Punktdiagramm: Haltedauer gegen P&L.', info: 'Jeder Punkt ist ein geschlossener Trade: waagerecht die Haltedauer (logarithmisch), senkrecht das Netto-Ergebnis.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); const pts = d.closed.filter(t => t.holdingMin != null).map(t => ({ x: Math.log10(t.holdingMin + 1), y: t.pnl, tip: `<b>${esc(t.symbol)}</b> ${fmt.dur(t.holdingMin)}<br>${fmt.cur(t.pnl, { signed: true })}` })); U.chartData['dash-haltedauer'] = { points: pts, xTicks: HOLD_TICKS.map(([m, l]) => ({ v: Math.log10(m + 1), label: l })) }; return card(e, `<div class="chart h280" data-chart="scatter" data-id="dash-haltedauer"></div>`); } },
    { typ: 'pnl_pro_tag', name: 'Netto-P&L pro Tag', preview: 'bars', groesse: 'klein', desc: 'Säulendiagramm mit grünen und roten Säulen je Handelstag.', info: 'Netto-Ergebnis je Handelstag im Zeitraum. Grüne Säulen sind Gewinntage, rote Verlusttage.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); U.chartData['dash-tag'] = { days: d.days }; return card(e, `<div class="chart h280" data-chart="dbars" data-id="dash-tag"></div>`); } },
    { typ: 'taeglich_kumuliert', name: 'Täglicher & kumulierter P&L', preview: 'combo', groesse: 'klein', desc: 'Säulen für den Tages-P&L und Fläche für den kumulierten P&L in einem Diagramm.', info: 'Säulen: Netto-Ergebnis je Handelstag. Fläche und Linie: kumuliertes Ergebnis im Zeitraum.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); U.chartData['dash-combo'] = { days: d.days, bars: true }; return card(e, `<div class="chart h280" data-chart="pnl" data-id="dash-combo"></div>`); } },
    { typ: 'letzte_trades', name: 'Letzte Trades & offene Positionen', preview: 'table', groesse: 'klein', desc: 'Tabelle mit Datum, Symbol und P&L. Tabs für letzte Trades und offene Positionen.', info: 'Die zuletzt geschlossenen Trades des Kontos und alle noch offenen Positionen.',
      render(d, inst, e, App) {
        const tab = App.state.recentTab || 'recent'; const open = d.all.filter(t => !t.closed).sort((a, b) => b.open - a.open); const recent = d.all.filter(t => t.closed).sort((a, b) => b.close - a.close).slice(0, 8); const rows = tab === 'open' ? open : recent;
        const table = rows.length ? `<div class="tbl-wrap inset"><table class="tbl compact" style="min-width:0"><thead><tr><th>${tab === 'open' ? 'Eröffnet' : 'Geschlossen'}</th><th>Symbol</th><th class="r">${tab === 'open' ? 'Risiko' : 'Netto-P&L'}</th></tr></thead><tbody>${rows.map(t => `<tr class="link" data-action="trade" data-id="${t.id}"><td>${fmt.dateFull(tab === 'open' ? t.open : t.close)}</td><td class="sym">${esc(t.symbol)} ${U.badge(t.direction)}</td><td class="r">${tab === 'open' ? (t.risk ? fmt.cur(t.risk) : '—') : U.pnl(t.pnl)}</td></tr>`).join('')}</tbody></table></div>` : `<div class="empty" style="min-height:160px">${I.tradelog}<b>${tab === 'open' ? 'Keine offenen Positionen' : NO_DATA}</b></div>`;
        return U.card(e.name, `<div class="tabs sm" style="margin-bottom:12px">${[['recent', 'Letzte Trades'], ['open', `Offene Positionen${open.length ? ` (${open.length})` : ''}`]].map(([k, l]) => `<button type="button" data-action="recent-tab" data-value="${k}" aria-pressed="${tab === k}">${l}</button>`).join('')}</div>${table}`, { info: e.info });
      } },
    { typ: 'kalender', name: 'Kalender', preview: 'calendar', groesse: 'mittel', desc: 'Monatsansicht: Tage grün, rot oder grau mit P&L und Anzahl Trades. Pfeile zum Monatswechsel.', info: 'Ein Feld pro Tag mit Netto-Ergebnis und Anzahl Trades: grün bei Gewinn, rot bei Verlust, grau bei Break-even. Klick öffnet die Tagesansicht.',
      render(d, inst, e, App) { const now = new Date(); const m = App.state.calMonth || new Date(now.getFullYear(), now.getMonth(), 1); return U.card(e.name, `<div class="row between" style="margin-bottom:12px">${calNav(m, 'cal-prev', 'cal-next', 'cal-today')}<div class="small muted">${monthSub(d.daysAll, m)}</div></div>${calendarHTML(d.daysAll, m.getFullYear(), m.getMonth())}`, { info: e.info }); } },
    { typ: 'kontostand', name: 'Kontostand-Verlauf', preview: 'line', groesse: 'klein', desc: 'Linie: Startkapital plus Netto-P&L über die Zeit.', info: 'Kontogröße aus den Einstellungen plus kumuliertes Netto-Ergebnis je Handelstag. Die gestrichelte Linie ist das Startkapital.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); let cum = 0; const pts = d.days.map(x => { cum += x.pnl; return { date: x.day, v: d.account + cum, pnl: x.pnl }; }); U.chartData['dash-kontostand'] = { points: pts, baseline: d.account }; return card(e, `<div class="chart h280" data-chart="line" data-id="dash-kontostand"></div><div class="legend"><span><i style="background:var(--accent)"></i>Kontostand</span><span><i style="background:var(--muted)"></i>Startkapital</span></div>`); } },
    { typ: 'drawdown_verlauf', name: 'Drawdown-Verlauf', preview: 'dd', groesse: 'klein', desc: 'Flächendiagramm des Rückgangs vom Höchststand über die Handelstage.', info: 'Abstand der kumulierten Ergebniskurve zu ihrem bisherigen Hoch je Handelstag. Null heißt: neues Hoch.',
      render(d, inst, e) { if (d.empty) return card(e, emptyBox(280)); U.chartData['dash-dd'] = { points: d.dd.series }; return card(e, `<div class="chart h280" data-chart="dd" data-id="dash-dd"></div><div class="small muted" style="margin-top:6px">Max. Drawdown: <b class="neg">${fmt.cur(d.dd.max)}</b>${d.dd.maxAt ? ` am ${fmt.dateFull(d.dd.maxAt)}` : ''}</div>`); } },
    { typ: 'challenge', name: 'Challenge', preview: 'progress', groesse: 'klein', settings: 'challenge', desc: 'Fortschrittsbalken zu einem eigenen Ziel, z. B. Gewinnziel und maximaler Verlust einer Prop-Firm-Challenge.', info: 'Gewinnziel und Verlustlimit legst du über das Zahnrad fest. Der obere Balken zeigt den Weg zum Ziel, der untere, wie viel vom erlaubten Verlust verbraucht ist. Optional ab einem Startdatum.',
      render(d, inst, e) {
        const cfg = inst.einstellungen || {}; const ziel = Number(cfg.ziel) || 0, maxV = Number(cfg.maxVerlust) || 0, tagV = Number(cfg.tagesVerlust) || 0;
        if (!ziel && !maxV) return card(e, `<div class="dashed" style="min-height:120px;display:grid;place-items:center;text-align:center">Noch kein Ziel festgelegt.<br><span class="small">Klicke auf das Zahnrad und trage Gewinnziel und maximalen Verlust ein.</span></div>`, { trailing: settingsBtn() });
        const from = cfg.start ? C.parseDayKey(cfg.start) : null; const list = from ? C.closedOnly(d.all).filter(t => t.close >= from) : d.closed; const days = C.dailyAggregation(list); const pnl = C.sum(days.map(x => x.pnl)); const dd = C.drawdownStats(days, d.account); const worstDay = days.length ? Math.min(...days.map(x => x.pnl)) : 0;
        const goalF = ziel ? C.clamp(pnl / ziel, 0, 1) : 0; const lossUsed = Math.max(0, -Math.min(pnl, dd.max)); const lossF = maxV ? C.clamp(lossUsed / maxV, 0, 1) : 0;
        const status = maxV && lossUsed >= maxV ? `<span class="pill loss">Verlustlimit verletzt</span>` : ziel && pnl >= ziel ? `<span class="pill win">Ziel erreicht</span>` : `<span class="pill neutral">Läuft${from ? ` seit ${fmt.dateFull(from)}` : ''}</span>`;
        const bar = (label, f, text, color) => `<div class="bar-row"><div class="bl"><span>${label}</span><b>${text}</b></div><div class="track"><i style="width:${(f * 100).toFixed(1)}%;background:${color}"></i></div></div>`;
        return card(e, `<div class="row between" style="margin-bottom:6px"><div class="big-stat" style="font-size:30px;margin:0"><span class="${U.cls(pnl)}">${fmt.cur(pnl, { signed: true })}</span></div>${status}</div>${ziel ? bar('Gewinnziel', goalF, `${fmt.pct(goalF)} von ${fmt.cur(ziel, { compact: true })}`, 'var(--profit)') : ''}${maxV ? bar('Maximaler Verlust', lossF, `${fmt.cur(lossUsed)} von ${fmt.cur(maxV, { compact: true })}`, 'var(--loss)') : ''}${tagV ? bar('Schlechtester Tag', C.clamp(-worstDay / tagV, 0, 1), `${fmt.cur(worstDay)} (Limit ${fmt.cur(-tagV)})`, 'var(--warn)') : ''}${list.length ? `<div class="small muted" style="margin-top:8px">${list.length} Trades · ${days.length} Handelstage</div>` : `<div class="small muted" style="margin-top:8px">${NO_DATA}</div>`}`, { trailing: settingsBtn() });
      } },
    { typ: 'mini_kalender', name: 'Mini-Kalender', preview: 'calendar', groesse: 'klein', desc: 'Kompakte Monatsansicht, nur grün und rot ohne Zahlen.', info: 'Kompakter Monatsblick: grün bei Gewinntag, rot bei Verlusttag, grau bei Break-even. Beim Drüberfahren erscheint das Ergebnis.',
      render(d, inst, e, App) { const now = new Date(); const m = App.state.calMonth || new Date(now.getFullYear(), now.getMonth(), 1); return U.card(e.name, `<div style="margin-bottom:8px">${calNav(m, 'cal-prev', 'cal-next', '')}</div>${calendarHTML(d.daysAll, m.getFullYear(), m.getMonth(), { mini: true })}<div class="small muted" style="margin-top:8px">${monthSub(d.daysAll, m)}</div>`, { info: e.info }); } },
    { typ: 'kalender_erweitert', name: 'Erweiterter Kalender', preview: 'calext', groesse: 'mittel', desc: 'Wie Kalender, mit einer zusätzlichen Spalte rechts mit dem P&L jeder Woche.', info: 'Monatsansicht mit Netto-Ergebnis je Tag und rechts das Wochenergebnis mit Anzahl der Handelstage.',
      render(d, inst, e, App) { const now = new Date(); const m = App.state.calMonth || new Date(now.getFullYear(), now.getMonth(), 1); return U.card(e.name, `<div class="row between" style="margin-bottom:12px">${calNav(m, 'cal-prev', 'cal-next', 'cal-today')}<div class="small muted">${monthSub(d.daysAll, m)}</div></div>${calendarHTML(d.daysAll, m.getFullYear(), m.getMonth(), { weeks: true })}`, { info: e.info }); } },
    { typ: 'regel_tracker', name: 'Regel-Tracker', preview: 'heat', groesse: 'mittel', desc: 'Heatmap wie bei GitHub: je dunkler, desto mehr Regeln an dem Tag eingehalten.', info: 'Ein Kästchen pro Tag der letzten 26 Wochen. Je mehr deiner Handelsregeln du an dem Tag abgehakt hast, desto kräftiger die Farbe. Regeln pflegst du in den Einstellungen, abhaken im Fortschritt-Tab.',
      render(d, inst, e) {
        const rules = S.data.rules.filter(r => r.active !== false); if (!rules.length) return card(e, `<div class="dashed" style="min-height:120px;display:grid;place-items:center;text-align:center">Noch keine Regeln angelegt.<br><span class="small">Lege deine Handelsregeln in den Einstellungen an, dann erscheint hier deine Regeltreue pro Tag.</span></div>`, { trailing: `<a class="btn sm" href="#/settings">Regeln anlegen</a>` });
        const end = new Date(); end.setHours(0, 0, 0, 0); const start = C.weekStart(end); start.setDate(start.getDate() - 25 * 7); const cells = []; const c = new Date(start); const lead = (start.getDay() + 6) % 7; for (let i = 0; i < lead; i++) cells.push('<i style="visibility:hidden"></i>');
        let tracked = 0, sum = 0;
        while (c <= end) { const k = C.dayKey(c); const day = S.day(k); const f = day && day.rulesFollowed ? day.rulesFollowed.filter(id => rules.some(r => r.id === id)).length / rules.length : null; if (f != null) { tracked++; sum += f; } const lvl = f == null ? '' : f >= 0.99 ? 'l4' : f >= 0.66 ? 'l3' : f >= 0.33 ? 'l2' : 'l1'; cells.push(`<i class="${lvl}" data-tip="<b>${fmt.dateFull(c)}</b><br>${f == null ? 'Kein Regel-Check' : `${Math.round(f * rules.length)} von ${rules.length} Regeln eingehalten`}" data-action="day" data-day="${k}"></i>`); c.setDate(c.getDate() + 1); }
        return card(e, `<div class="heat big">${cells.join('')}</div><div class="row between" style="margin-top:10px"><div class="heat-legend" style="margin:0"><span>Weniger</span><i class="l1"></i><i class="l2"></i><i class="l3"></i><i class="l4"></i><span>Mehr</span></div><div class="small muted">${tracked ? `Ø ${fmt.pct(sum / tracked)} an ${tracked} Tagen` : 'Noch kein Regel-Check'}</div></div>`);
      } },
    { typ: 'report', name: 'Report', preview: 'line', groesse: 'mittel', settings: 'report', desc: 'Bis zu drei Kennzahlen nach Wahl als Liniendiagramm im Zeitverlauf.', info: 'Laufende Werte je Handelstag für die gewählten Kennzahlen. Über das Zahnrad wählst du bis zu drei Kennzahlen.',
      render(d, inst, e) { const keys = ((inst.einstellungen || {}).kennzahlen || ['trefferquote', 'netto_pnl']).filter(k => REPORT_METRICS[k]).slice(0, 3); if (d.empty) return card(e, emptyBox(280), { trailing: settingsBtn() }); const series = keys.map((k, i) => Object.assign({ key: REPORT_METRICS[k].key, label: REPORT_METRICS[k].label, unit: REPORT_METRICS[k].unit, color: LINE_COLORS[i] })); U.chartData['dash-report'] = { points: d.running.map(r => ({ date: r.date, v: r })), series }; return card(e, `<div class="chart h280" data-chart="lines" data-id="dash-report"></div><div class="legend">${series.map(s => `<span><i style="background:${s.color}"></i>${esc(s.label)}</span>`).join('')}</div>`, { trailing: settingsBtn() }); } },
    { typ: 'jahreskalender', name: 'Jahreskalender', preview: 'year', groesse: 'gross', desc: '12 kleine Monate in einem Raster, Tage grün oder rot eingefärbt.', info: 'Alle zwölf Monate eines Jahres auf einen Blick. Grün bei Gewinntag, rot bei Verlusttag, grau bei Break-even. Pfeile wechseln das Jahr.',
      render(d, inst, e, App) { const y = App.state.dashYear || new Date().getFullYear(); return U.card(e.name, yearHTML(d.daysAll, y), { info: e.info, trailing: `<div class="cal-nav"><button type="button" class="btn round" data-action="dash-year" data-dir="-1" aria-label="Voriges Jahr">${I.chevL}</button><b style="min-width:48px;text-align:center">${y}</b><button type="button" class="btn round" data-action="dash-year" data-dir="1" aria-label="Nächstes Jahr">${I.chevR}</button></div>` }); } },
  ];
  const settingsBtn = () => `<button type="button" class="btn ghost icon sm w-cfg" data-action="dash-w-settings" title="Einstellungen" aria-label="Widget-Einstellungen">${I.settings}</button>`;

  const ALL = {}; for (const e of TOP) ALL[e.typ] = Object.assign(e, { area: 'oben' }); for (const e of MAIN) ALL[e.typ] = Object.assign(e, { area: 'unten' });

  root.Widgets = {
    SIZES, MAX_TOP, REPORT_METRICS, ALL,
    list(area) { return (area === 'oben' ? TOP : MAIN).slice(); },
    get(typ) { return ALL[typ] || null; },
    data: makeData, preview, calendarHTML,
    render(inst, d, App) { const e = ALL[inst.typ]; if (!e) return U.card('Unbekanntes Widget', `<div class="small muted">Der Widget-Typ „${esc(inst.typ)}“ ist nicht bekannt.</div>`); try { return e.render(d, inst, e, App); } catch (err) { console.warn('Widget', inst.typ, err); return U.card(e.name, `<div class="small muted">Dieses Widget konnte nicht berechnet werden.</div>`, { info: e.info }); } },
  };
})(typeof self !== 'undefined' ? self : this);
